package com.secretbiology.taboo.words;

//This set was modified from following websites :
// (1) https://embracingchina.files.wordpress.com/2014/08/taboo-game.pdf on 28th May 2016
// (2) https://en.islcollective.com

public class WordSet1 {

    public String[][] words(){
        String[][] allwords = {
                {"Blanket", "Warm", "Bed", "Pillow", "Soft", "Cold"},
                {"Shanghai", "Modern", "Big", "China", "Expo", "Famous"},
                {"Soccer", "Ball", "World Cup", "Black", "Sport", "Team"},
                {"Cheese", "Yellow", "White", "Pizza", "Food", "Italy"},
                {"Snail", "Round", "Slow", "River", "Eat", "Animal"},
                {"Husband", "Wife", "Ring", "Marry", "Man", "Friend"},
                {"Michael Jackson", "Dance", "Thriller", "Strange", "Famous", "Singer"},
                {"Underwear", "Small", "Clothing", "Every day", "Secret", "Under"},
                {"Girlfriend", "Boyfriend", "Beautiful", "Flowers", "Date", "female"},
                {"Giraffe", "Tall", "Africa", "Neck", "Long", "Yellow"},
                {"Wok", "Cook", "China", "Iron", "Dishes", "Pot"},
                {"Camera", "Photos", "Pictures", "Snapshot", "Travel", "Memories"},
                {"Slippers", "Warm", "Feet", "Winter", "House", "Soft"},
                {"Comb", "Brush", "Hair", "Smooth", "Small", "Beautiful"},
                {"Hamburger", "America", "Beef", "Bread", "McDonalds", "Unhealthy"},
                {"Polar Bear", "Cold", "Winter", "Alaska", "White", "Snow"},
                {"Penguin", "Bird", "Fly", "Animal", "Black", "White"},
                {"Glasses", "Eyes", "See", "Contacts", "Wear", "Face"},
                {"Popcorn", "Kernel", "Butter", "Sweet", "Microwave", "Snack Food"},
                {"Speech", "Give", "Speak", "Important", "Audience", "Nervous"},
                {"Furious", "Angry", "Red Face", "Hurt", "Rage", "Violent"},
                {"Jealousy", "Envy", "Emotion", "Compare", "Green", "Achieve"},
                {"Chicken Leg", "Bird", "Body", "Eat", "Food", "KFC"},
                {"Toilet", "Washroom", "WC", "Pee", "Poop", "Bathroom"},
                {"Wish", "Want", "Desire", "Hope", "Dream", "Long For"},
                {"Bench", "Sit", "Wooden", "Chair", "Long", "Park"},
                {"Exercise", "Run", "Sports", "Healthy", "Daily", "Morning"},
                {"Crown", "Head", "Gold", "King", "Queen", "Jewels"},
                {"Princess", "Prince", "Queen", "Daughter", "Royal", "Castle"},
                {"Internet", "Computer", "Web", "Surf", "Net", "Technology"},
                {"Jacket", "Coat", "Warm", "Clothes", "Sleeves", "Zipper"},
                {"Shower", "Rain", "Clean", "Water", "Every Day", "Bath"},
                {"Wind", "Blow", "Autumn", "Invisible", "Trees", "Kite"},
                {"Ice Cream", "Cold", "Summer", "Sweet", "Snack", "Cone"},
                {"Foreigner", "Teacher", "Different", "Outside", "Country", "Travel"},
                {"Church", "Sing", "Building", "Cross", "God", "Speaker"},
                {"Police", "Uniform", "Safety", "Peace", "Protect", "Siren"},
                {"Boots", "Winter", "Shoes", "Warm", "Fashion", "Snow"},
                {"Plane Ticket", "Expensive", "Flight", "Travel", "Paper", "Seat"},
                {"Turkey", "Bird", "Holiday", "Thanksgiving", "Big", "Tired"},
                {"Freezer", "Cold", "Refrigerator", "Ice", "Food", "Kitchen"},
                {"Soy Sauce", "Chinese", "Liquid", "Brown", "Cooking", "Salty"},
                {"Yoga Teacher", "Exercise", "Instructor", "Master", "Chinese", "Help"},
                {"Straw", "Hollow", "Horses", "Farm", "Drink", "Suck"},
                {"Leaf", "Tree", "Green", "Fall", "Plant", "Page"},
                {"Noun", "Verb", "Speech", "Adjective", "Person", "Place"},
                {"Carry", "Hold", "Pick up", "Move", "Transport", "Support"},
                {"Taxi", "Car", "Public", "Transport", "Fare", "City"},
                {"Blossom", "Flower", "Young", "Bud", "Spring", "Bloom"},
                {"Broom", "Sweep", "Floor", "Witch", "Wooden", "Dust"},
                {"Witch", "Broom", "Green", "Magic", "Halloween", "Powers"},
                {"Fork", "Spoon", "Knife", "Eat", "Prongs", "Divide"},
                {"Parade", "Line", "Crowd", "Floats", "Gather", "Holiday"},
                {"Fashion", "Clothes", "Model", "Girls", "Look", "Magazine"},
                {"Weeding Dress", "White", "Married", "Clothes", "Special", "Girls"},
                {"Kung Fu Panda", "Movie", "China", "Noodles", "Children", "Famous"},
                {"Marker", "Write", "Draw", "Colors", "Children", "Art"},
                {"Trash Can", "Rubbish", "Barrel", "Worthless", "Ruin", "Old"},
                {"Snowman", "Three", "Children", "Make", "Winter", "Outside"},
                {"Wings", "Bird", "Chicken", "Fly", "Arms", "Feathers"},
                {"Pilot", "Fly", "Plane", "Helicopter", "Man", "Travel"},
                {"Lawyer", "Argue", "Defend", "Law", "Client", "Crime"},
                {"Hair Salon", "Style", "Dye", "Wash", "Cut", "Barber"},
                {"Picture Frame", "Photo", "Memory", "Wood", "Glass", "Home"},
                {"Purse", "Leather", "Bag", "Money", "Women", "Carry"},
                {"Alligator", "Crocodile", "Green", "Animal", "Teeth", "Florida"},
                {"Orange", "Color", "Fruit", "Juicy", "Citrus", "Red"},
                {"Makeup", "Face", "Mascara", "Lipstick", "Girls", "Beautiful"},
                {"Tutor", "One on One", "Learn", "Make up", "Review"},
                {"Worry","Nervous", "Anxiety", "Stress", "Scared", "Trouble"},
                {"Moose", "Animal", "Mammal", "Forest", "Antlers", "Hunting"},
                {"Shampoo", "Conditioner", "Lather", "Wash", "Hair", "Shower"},
                {"Bridge", "Cross", "River", "Build", "Over", "Connect"},
                {"Nervous", "Anxious", "Test", "Difficulty", "Pressure", "Scared"},
                {"Camel", "Hump", "Desert", "Animal", "Water", "Cigarette"},
                {"Watch", "Look", "Stare", "Wrist", "Time", "Jewelery"},
                {"Brush", "Comb", "Hair", "Bristles", "Wooden", "Stroke"},
                {"License", "Driver", "Car", "Card", "Permit", "Allow"},
                {"Librarian", "Books", "Library", "School", "Job", "Quiet"},
                {"Liberty", "Freedom", "Statue", "Power", "Choose", "Decide"},
                {"Radio", "Listen", "Music", "AM", "FM", "News"},
                {"Shout", "Yell", "Loud", "Speak", "Angry", "Danger"},
                {"Unlock", "Key", "Door", "Box", "Safe", "Hole"},
                {"Pear", "Apple", "Fruit", "Shape", "Tree", "Juice"},
                {"Jumping", "Leap", "Up", "Down", "Excited", "Action"},
                {"Glove", "Hand", "Cold", "Winter", "Disposable", "Mitten"},
                {"Tornado", "Storm", "Dorothy", "Swirl", "Wind", "Blow"},
                {"Wheelchair", "Cripple", "Handicapped", "Legs", "Old", "Elderly"},
                {"Monster", "Scary", "Green", "Alien", "Zombie", "Creature"},
                {"Midterm", "Test", "Exam", "Half", "Final", "School"},
                {"Melt", "Soft", "Warm", "Ice", "Heat", "Liquid"},
                {"Mature", "Old", "Wise", "Develop", "Grown", "Advance"},
                {"Daisy", "White", "Yellow", "Flower", "Duck", "Field"},
                {"Custom", "Culture", "Way", "Tradition", "Behave", "Society"},
                {"Curtain", "Red", "Window", "Light", "Cloth", "Play"},
                {"Cruel", "Mean", "Angry","Unkind", "Pain", "Suffering"},
                {"Milk", "White", "Liquid", "Drink", "Bones", "Cow"},
                {"Politics", "Law", "President", "Leaders", "Country", "Citizen"},
                {"Guitar", "Instrument", "Play", "Strings", "Strum", "Music"},
                {"Chalk", "White", "Dust", "Teach", "Blackboard", "Erase"},
                {"Bottle", "Feed", "Baby", "Glass", "Juice", "Water"},
                {"Table", "Eat", "Chairs", "Legs", "Study", "Wooden"},
                {"Distance", "Length", "Mile", "Meter", "Space", "Far Away"},
                {"Elderly", "Old", "Nurse", "Aged", "Adult", "Health"},
                {"Fish", "Swim", "Gills", "River", "Eat", "Catch"},
                {"Famous", "Popular", "Known", "Important", "Recognize", "Position"},
                {"New York", "Statue", "Apple", "City", "America", "Busy"},
                {"Train", "Ride", "Travel", "Cheap", "Railroad", "Choo-choo"},
                {"Needle", "Haystack", "Sharp", "Small" ,"metal", "Sew"},
                {"Joy", "Happy", "Celebrate", "Excited", "Pleasure", "Feeling"},
                {"Firecracker", "Explode", "Loud", "Red", "Light", "Holiday"},
                {"Superman", "Fly", "Hero", "Bird", "Plane", "Clark Kent"},
                {"Sun", "Warm", "Yellow", "Light", "Solar", "Planet"},
                {"Monkey", "Swing", "Banana", "Zoo", "Brown", "Animal"},
                {"Shark", "Swim", "Teeth", "Fish", "Ocean", "Dangerous"},
                {"Desk", "Homework", "Sit", "Wooden", "Table", "Classroom"},
                {"Coffee", "Tea", "Drink", "Awake", "Starbucks", "CCD"},
                {"Egg Roll", "Spring", "Vegetable", "Round", "Chaina", "Food"},
                {"Santa", "Fat", "Christmas", "Gifts", "Red", "North Pole"},
                {"Bells", "Ring", "Silver", "Hear", "Metal", "Gold"},
                {"Heart", "Love", "Shape", "Beat", "Broken", "Blood"},
                {"Headache", "Pound", "Medicine", "Sick", "Brain", "Rush"},
                {"Discuss", "Talk", "Debate", "Ideas", "Oppose", "Share"},
                {"Debate", "Discus", "Sides", "Talk", "Oppose", "Win"},
                {"Eraser", "Clean", "Pencil", "Fix", "Mistake", "Change"},
                {"Prisoner", "Jail", "Convict", "Murder", "Crime", "Police"},
                {"Murder", "Kill", "Prison", "Jail", "Law", "Court"},
                {"Defend", "Lawyer", "Judge", "Stand Up", "Justify", "Reality"},
                {"Deer", "Animal", "Antlers", "Hunting", "Forest", "Bambi"},
                {"Zoo", "Animals", "Place", "Tigers", "Elephants", "Cage"},
                {"Crawl", "Fours", "Baby", "Toddlers", "Hands", "Knees"},
                {"Bank", "Robbery", "Money", "Safe", "Deposit", "Invest"},
                {"Caterpillar", "Crawl", "Insect", "Tree", "Butterfly", "Transformation"},
                {"Pregnant", "Baby", "Fat", "Belly", "Life", "9 Months"},
                {"Towel", "Dry", "Dishes", "Shower", "Soft", "Beach"},
                {"Promise", "Vow", "Pledge", "Expect", "Reassure", "Marry"},
                {"Ugly", "Duck", "Beautiful", "Hideous", "Deformed", "Butt"},
                {"Stupid", "Smart", "Cleaver", "Dull", "Dumb", "Intelligent"},
                {"Spoon", "Fork", "Knife", "Eating", "Soup", "Metal"},
                {"Infant", "Baby", "Cry", "Child", "Newborn", "Young"},
                {"Paris", "Romantic", "Shopping", "France", "Eiffel", "Tower"},
                {"Exchange Student", "Travel", "Study", "Abroad", "Experience", "Foreign"},
                {"Gold", "Silver", "Metal", "Rich", "Money", "King"},
                {"London", "England", "Europe", "U.K.", "Capital", "Big Ben"},
                {"Camping", "Tent", "Outside", "Fire", "Roast", "Sleep"},
                {"Theater", "Movie", "Drama", "Popcorn", "Cinema", "Actor"},
                {"Death", "Die", "Old", "Murder", "Life", "Cause"},
                {"Flag", "Wave", "Fly", "Old Glory", "Pole", "Fabric"},
                {"Describe", "Talk About", "Words", "Characteristics", "Quality", "Depict"},
                {"Fly", "Wings", "Bird", "Airplane", "Insect", "Bee"},
                {"Knee", "Bend", "Joint", "Leg", "Body Part", "Cap"},
                {"Web", "Internet", "Spider", "World Wide", "Net" , "Network"},
                {"Worm", "Crawl", "Animal", "Wriggle", "Slimy", "Rain"},
                {"Machine", "Parts", "Device", "Metal", "Power", "Cog"},
                {"Spiderman", "Peter Parker", "Marvel", "Comic Hero", "Webs", "Insect"},
                {"Waitress", "Service", "Restaurant", "Food", "Helper", "Worker"},
                {"Wash", "Clean", "Shower", "Dishes", "Hair", "Laundry"},
                {"Biology", "Sceince", "Subject", "Life", "School", "Cell"},
                {"Chemistry", "Sceince", "Subject", "Chemicals", "School", "Major"},
                {"History", "Politics", "Past", "Events", "Finished", "Happened"},
                {"Magazine", "Pages", "Book", "Entertain", "News", "Read"},
                {"Unfair", "Unjust", "Fair", "Equal", "Unreasonable", "Breakup"},
                { "CD", "Computer", "Disc", "Music", "Movies", "Play"},
                {"Immediately", "Fast", "Now", "Delay", "Rapid", "Soon"},
                {"Danger", "Safe", "Harm", "Injury", "Protect", "Avoid"},
                {"Blanket", "Bed", "Pillow", "Quilt", "Soft", "Warm"},
                {"Ice", "Cold", "Solid", "Water", "Freezer", "Winter"},
                {"Salt", "White", "Food", "Popcorn", "Cooking", "Flavour"},
                {"Stand", "Sit", "Floor", "Feet", "Up", "Take"},
                {"Bull", "Ride", "Animal", "Strong", "Farm", "Red"},
                {"Peaceful", "Harmony", "Calm", "Quiet", "Tranquil", "Violent"},
                {"Normal", "Strange", "Standard", "Typical", "Weird", "Status Quo"},
                {"Original", "First", "Unique", "Special", "Standard", "Early"},
                {"Magic", "Wizard", "Witch", "Power", "Trick", "Show"},
                {"Naughty", "Bad", "Behavior", "Good", "Rude", "Disobedient"},
                {"Rescue", "Save", "Hero", "Danger", "Safe", "Help"},
                {"Match", "Fire", "Strike", "Pair", "Game", "Equal"},
                {"Hippo", "Fat" ,"Animal", "Africa", "Large", "Water"},
                {"Fairy Tale", "Prince", "Magic", "Queen", "Story", "Fiction"},
                {"Literature", "Works", "American", "British", "Books", "Written"},
                {"Globe", "Earth", "World", "Model", "Geography", "Round"},
                {"Cook Book", "Food", "How to", "Kitchen", "Manual", "Guide"},
                {"Continent", "Ocean", "Asia", "Land", "Seven", "Earth"},
                {"Director", "Movie", "Producer", "Main", "In Charge", "Position"},
                {"Advice", "Guide", "Wise", "Recommend", "What to do", "Help"},
                {"You", "Me", "I", "Him", "Her", "Pronoun"},
                {"Cafe", "Food", "Snack", "Coffee", "Drink", "Eat"},
                {"Television", "Watch", "Cartoon", "Movies", "Channel", "TV"},
                {"Violin", "Strings", "Orchestra", "Music", "Instrument", "Concert"},
                {"Boat", "Water", "Sea", "Ship", "Captain", "Transport"},
                {"Father", "Parent", "Husband", "Man", "Family", "Work"},
                {"Rain", "Precipitation", "Water", "Sky", "Clouds", "Drops"},
                {"Clown", "Joker", "Circus", "Red Nose", "Mc-Donalds", "Make-up"},
                {"Ipod", "Music Player", "Apple", "MP3", "Iphone", "Songs"},
                {"Lipstick", "Red", "Lips", "Purse", "Women", "Make-up"},
                {"Fear", "Phobia", "Scare", "Taboo", "Terror", "Spiders"},
                {"Sea", "Blue", "Sky", "Water", "Red", "Ocean"},
                {"Chicken", "Food", "Meat", "Egg", "KFC", "Rooster"},
                {"Napkin", "Wipe", "Mouth", "Clean", "Stack", "Spill"},
                {"Diamond", "Rock", "Engagement", "Ring", "Jewel", "Stone"},
                {"Bee", "Honey", "Insect", "Hive", "Sting", "Bumble"},
                {"Honey", "Bee", "Sweet", "Hive", "Food", "Allergy"},
                {"Milk", "White", "Cereal", "Dairy", "Liquid", "Cow"},
                {"Dance", "Move", "Music", "Party", "Club", "Bands"},
                {"Gorilla", "Eats Banana", "Animal", "Scary", "Monkey", "Africa"},
                {"Glass", "Cup", "Drink", "Plate", "Kitchen", "Utensil"},
                {"Money", "Bank", "ATM", "Wallet", "Buy", "Currency"},
                {"Dangdut", "Dance", "Music", "Popular", "Indonesia", "Genre"},
                { " Mile " ,  " Length " ,  " Measurement " ,  " Feet ",  " Inches " ,  " Kilometer "} ,
                { " Cheese " ,  " Swiss " ,  " Melt " ,  " Dairy ",  " Sharp " ,  " Cheddar "} ,
                { " Hey " ,  " Call " ,  " Me " ,  " On ",  " This " ,  " Number "} ,
                { " Quartz " ,  " Mineral " ,  " Rock " ,  " Music ",  " Gem " ,  " Crystal "} ,
                { " Prayer " ,  " Pray " ,  " God " ,  " Church ",  " Kneel " ,  " Eyes "} ,
                { " Telescope " ,  " Look " ,  " Scope " ,  " Stars ",  " Planet " ,  " Sky "} ,
                { " Hotshot " ,  " Fire " ,  " Wildfire " ,  " Water ",  " Firefighter " ,  " Department "} ,
                { " Scruple " ,  " Scrap " ,  " Shred " ,  " Speck ",  " Whit " ,  " Tittle "} ,
                { " Bees " ,  " Sting " ,  " Yellow " ,  " Black ",  " Hive " ,  " Honey "} ,
                { " Hangar " ,  " Stay " ,  " Hip " ,  " Tiger ",  " Jump " ,  " Cook "} ,
                { " Freckle " ,  " Face " ,  " Spot " ,  " Dot ",  " Pimple " ,  " Sun "} ,
                { " Brick " ,  " Red " ,  " Old " ,  " Rustic ",  " Building " ,  " Heavy "} ,
                { " Develop " ,  " Generate " ,  " Produce " ,  " Evolve ",  " Unfold " ,  " Create "} ,
                { " Switch " ,  " Whip " ,  " Light " ,  " Swap ",  " Change " ,  " Flick "} ,
                { " Noun " ,  " Person " ,  " Place " ,  " Thing ",  " Idea " ,  " Feeling "} ,
                { " Report " ,  " Book " ,  " Above " ,  " Manager ",  " Summary " ,  " Speak "} ,
                { " Bacon " ,  " Pig " ,  " Breakfast " ,  " Eat ",  " Sausage " ,  " Eggs "} ,
                { " Track " ,  " Mark " ,  " Path " ,  " Structure ",  " Line " ,  " Soundtrack "} ,
                { " Currency " ,  " Dollars " ,  " Money " ,  " Cash ",  " Bank " ,  " Converter "} ,
                { " Gala " ,  " Festivity " ,  " Party " ,  " Occasion ",  " Affair " ,  " Celebration "} ,
                { " Badge " ,  " Cops " ,  " Law " ,  " Rules ",  " Ticket " ,  " Police "} ,
                { " Dinnerware " ,  " Cup " ,  " Bowl " ,  " Plate ",  " Fork " ,  " Knife "} ,
                { " Together " ,  " Group " ,  " Bunch " ,  " Gang ",  " Joined " ,  " United "} ,
                { " Route " ,  " Football " ,  " Bus " ,  " Directions ",  " Road " ,  " Path "} ,
                { " Optimist " ,  " Happy " ,  " Bright " ,  " Cheerful ",  " Negative " ,  " Delight "} ,
                { " Scandinavia " ,  " Sweden " ,  " Denmark " ,  " Finland ",  " Norway " ,  " Iceland "} ,
                { " Tablecloth " ,  " Table " ,  " Covering " ,  " Dinner ",  " White " ,  " Protect "} ,
                { " Vintage " ,  " Old " ,  " Retro " ,  " Used ",  " Wine " ,  " Antique "} ,
                { " Sock " ,  " Foot " ,  " Shoe " ,  " Clothing ",  " Wool " ,  " Hit "} ,
                { " Wellness " ,  " Fitness " ,  " Healthiness " ,  " Heartiness ",  " Wholesomeness " ,  " Liveliness "} ,
                { " Cooler " ,  " Heat " ,  " Fan " ,  " Beer ",  " Beverage " ,  " Sun "} ,
                { " Tulips " ,  " Holland " ,  " Flower " ,  " Poem ",  " Bud " ,  " Bouquet "} ,
                { " Pharmacist " ,  " Chemist " ,  " Drugs " ,  " Prescription ",  " Dispense " ,  " Profession "} ,
                { " Elastic " ,  " Rubber " ,  " Stretch " ,  " Sew ",  " Band " ,  " Return "} ,
                { " Tobacco " ,  " South " ,  " Slave " ,  " Cigarette ",  " Smoke " ,  " Nicotine "} ,
                { " Fisherman " ,  " Fishing " ,  " Pole " ,  " Catch ",  " Fish " ,  " Water "} ,
                { " Martini " ,  " Olive " ,  " Apple " ,  " Dirty ",  " Rocks " ,  " Fruity "} ,
                { " Straw " ,  " Drink " ,  " Long " ,  " Glass ",  " Soda " ,  " Tall "} ,
                { " Move " ,  " Relocate " ,  " Maneuver " ,  " Remove ",  " Shift " ,  " Transfer "} ,
                { " Companion " ,  " Counterpart " ,  " Mate " ,  " Match ",  " Fellow " ,  " Twin "} ,
                { " Armadillo " ,  " Ball " ,  " Shell " ,  " Armoured ",  " Animal " ,  " Small "} ,
                { " Cherry " ,  " Fruit " ,  " Pick " ,  " Seed ",  " Red " ,  " Cola "} ,
                { " Forge " ,  " Make " ,  " Build " ,  " Produce ",  " Frame " ,  " Construct "} ,
                { " Spray " ,  " Body " ,  " Smell " ,  " Water ",  " Perfume " ,  " Cleaner "} ,
                { " Knitting " ,  " Needles " ,  " Make " ,  " Scarf ",  " Wool " ,  " Jumper "} ,
                { " Ottoman " ,  " Chair " ,  " Turkey " ,  " Seat ",  " Sofa " ,  " Empire "} ,
                { " Booger " ,  " Nose " ,  " Stuffy " ,  " Green ",  " Gross " ,  " Pick "} ,
                { " Chocolate " ,  " Tasty " ,  " Sweet " ,  " Milk ",  " Dark " ,  " White "} ,
                { " Periphery " ,  " Circuit " ,  " Compass " ,  " Perimeter ",  " Circumference " ,  " Ambit "} ,
                { " Trial " ,  " Law " ,  " Game " ,  " Bike ",  " Usa " ,  " Software "} ,
                { " Slit " ,  " Cut " ,  " Opening " ,  " Throat ",  " Skirt " ,  " Wrist "} ,
                { " Butterfly " ,  " Cocoon " ,  " Metamorphosis " ,  " Larvae ",  " Wings " ,  " Colorful "} ,
                { " Extraordinary " ,  " Uncommon " ,  " Inquisitive " ,  " Extra ",  " Big " ,  " Interesting "} ,
                { " Acupuncture " ,  " Needles " ,  " Chinese " ,  " Medicine ",  " Pointy " ,  " Tradition "} ,
                { " Reconciliation " ,  " Balance " ,  " Matching " ,  " Investigation ",  " Debit " ,  " Credit "} ,
                { " Rough " ,  " Tough " ,  " Hard " ,  " Difficult ",  " Edge " ,  " Sandpaper "} ,
                { " Appliance " ,  " Contraption " ,  " Device " ,  " Apparatus ",  " Machine " ,  " Contrivance "} ,
                { " Sports " ,  " Football " ,  " Baseball " ,  " Basketball ",  " Soccer " ,  " Rugby "} ,
                { " Detail " ,  " Attention " ,  " Minute " ,  " Exact ",  " Perfect " ,  " Little "} ,
                { " Indefinite " ,  " Open " ,  " Uncertain " ,  " Undecided ",  " Vague " ,  " Unsure "} ,
                { " Maggie " ,  " Uncool " ,  " Unfunny " ,  " Slave ",  " Flawed " ,  " Showoff "} ,
                { " Brunette " ,  " Brown " ,  " Girl " ,  " Hair ",  " Easy " ,  " Blonde "} ,
                { " Rosemary " ,  " Herb " ,  " Spice " ,  " Name ",  " Flower " ,  " Thyme "} ,
                { " Important " ,  " Priority " ,  " Urgent " ,  " Top ",  " Now " ,  " First "} ,
                { " Dread " ,  " Fear " ,  " Alarm " ,  " Fright ",  " Panic " ,  " Terror "} ,
                { " Rhyme " ,  " Nursery " ,  " Poem " ,  " Limerick ",  " Song " ,  " Goose "} ,
                { " Community " ,  " Neighborhood " ,  " Vicinity " ,  " Surrounding ",  " Environment " ,  " Center "} ,
                { " Sterile " ,  " Germs " ,  " Bacteria " ,  " Clean ",  " Infection " ,  " Children "} ,
                { " Trinket " ,  " Knickknack " ,  " Whatnot " ,  " Toy ",  " Gewgaw " ,  " Novelty "} ,
                { " Campus " ,  " University " ,  " College " ,  " Land ",  " School " ,  " Study "} ,
                { " Oenophile " ,  " Connoisseur " ,  " Wines " ,  " Love ",  " Person " ,  " Study "} ,
                { " Grandson " ,  " Generation " ,  " Kids " ,  " Mom ",  " Children " ,  " Parent "} ,
                { " Xenia " ,  " Influence " ,  " Structure " ,  " Pollen ",  " Embryo " ,  " Effect "} ,
                { " Byte " ,  " Memory " ,  " Chew " ,  " Teeth ",  " Bit " ,  " Computer "} ,
                { " Economics " ,  " School " ,  " Economist " ,  " Studies ",  " Unemployment " ,  " Inflation "} ,
                { " Clip " ,  " Cut " ,  " Attach " ,  " Joiner ",  " Hit " ,  " Paperclip "} ,
                { " Apothecary " ,  " Potions " ,  " Ingredients " ,  " Herbs ",  " Magic " ,  " Shop "} ,
                { " Whisper " ,  " Low " ,  " Talk " ,  " Secret ",  " Hear " ,  " Speak "} ,
                { " Mars " ,  " Sun " ,  " System " ,  " Space ",  " Earth " ,  " Planet "} ,
                { " Fix " ,  " Repair " ,  " Accident " ,  " Handyman ",  " Tools " ,  " Screwdrivers "} ,
                { " Vex " ,  " Chagrin " ,  " Annoy " ,  " Petulant ",  " Peevish " ,  " Irritate "} ,
                { " Confirm " ,  " Verify " ,  " Ascertain " ,  " Agree ",  " Hearing " ,  " Yes "} ,
                { " Power " ,  " Speed " ,  " Strength " ,  " Electricity ",  " Fuel " ,  " Coal "} ,
                { " Virus " ,  " Trojan " ,  " Antivirus " ,  " Worm ",  " Computer " ,  " Laptop "} ,
                { " Macaroni " ,  " Pasta " ,  " Cheese " ,  " Food ",  " Kraft " ,  " Cheddar "} ,
                { " Wolves " ,  " Canine " ,  " Pack " ,  " Cold ",  " Husky " ,  " Howl "} ,
                { " Symmetry " ,  " Copy " ,  " Identical " ,  " Design ",  " Paper " ,  " Mirror "} ,
                { " Hide " ,  " Seek " ,  " Fur " ,  " Animal ",  " Game " ,  " Skin "} ,
                { " Intimation " ,  " Hint " ,  " Idea " ,  " Notion ",  " Possible " ,  " Clue "} ,
                { " Helipad " ,  " Helicopter " ,  " Airplane " ,  " Takeoff ",  " Landing " ,  " Depart "} ,
                { " Delight " ,  " Joy " ,  " Gladden " ,  " Enchant ",  " Cheer " ,  " Please "} ,
                { " Radio " ,  " Signal " ,  " Channel " ,  " Waves ",  " Station " ,  " Music "} ,
                { " Scholarship " ,  " Money " ,  " College " ,  " Pay ",  " Essay " ,  " Qualify "} ,
                { " Art " ,  " Creative " ,  " Skillful " ,  " Clever ",  " Culture " ,  " Painting "} ,
                { " Unicorn " ,  " Horn " ,  " Horse " ,  " Fantasy ",  " Mythical " ,  " White "} ,
                { " Gymnastics " ,  " Bars " ,  " Flip " ,  " Gym ",  " Leotard " ,  " Vault "} ,
                { " Missing " ,  " Gone " ,  " Dog " ,  " Lost ",  " There " ,  " Forgotten "} ,
                { " Spirit " ,  " Ghost " ,  " Poltergeist " ,  " Shade ",  " Dead " ,  " Sense "} ,
                { " Einstein " ,  " Scientist " ,  " German " ,  " Physics ",  " Nobel " ,  " Albert "} ,
                { " Rim " ,  " Glasses " ,  " Eye " ,  " Sight ",  " Wear " ,  " Body "} ,
                { " Backflip " ,  " Stunt " ,  " Cheerleading " ,  " Front ",  " Gymnastics " ,  " Skilled "} ,
                { " Sportscaster " ,  " Tv " ,  " Reporter " ,  " Microphone ",  " Animated " ,  " Smile "} ,
                { " Responsibility " ,  " Parents " ,  " School " ,  " Money ",  " Family " ,  " Lose "} ,
                { " Province " ,  " Area " ,  " Domain " ,  " Orbit ",  " Field " ,  " Realm "} ,
                { " Sketch " ,  " Artist " ,  " Draw " ,  " Pad ",  " Book " ,  " Courtroom "} ,
                { " Retain " ,  " Withhold " ,  " Keep " ,  " Reserve ",  " Hold " ,  " Own "} ,
                { " Lyrics " ,  " Song " ,  " Lines " ,  " Compose ",  " Musics " ,  " Poetry "} ,
                { " Vacuum " ,  " Suck " ,  " Carpet " ,  " Dust ",  " Clean " ,  " Chore "} ,
                { " Radar " ,  " Radio " ,  " Plane " ,  " Missile ",  " Ship " ,  " Submarine "} ,
                { " Relaxed " ,  " Calm " ,  " Breath " ,  " Restful ",  " Peaceful " ,  " Tranquil "} ,
                { " Portage " ,  " Walk " ,  " Canoe " ,  " Carry ",  " Across " ,  " Boat "} ,
                { " Puerile " ,  " Childish " ,  " Immature " ,  " Silly ",  " Juvenile " ,  " Adolescent "} ,
                { " Trap " ,  " Mouse " ,  " Hood " ,  " Stuck ",  " Rat " ,  " Ghetto "} ,
                { " Darkness " ,  " Shadow " ,  " Dark " ,  " Black ",  " Light " ,  " Scary "} ,
                { " Turbid " ,  " Murky " ,  " Roiled " ,  " Roily ",  " Muddy " ,  " Cloudy "} ,
                { " Atoll " ,  " Tropical " ,  " Desolate " ,  " Island ",  " Sand " ,  " Ocean "} ,
                { " Stapler " ,  " Clip " ,  " Paper " ,  " Together ",  " Bind " ,  " Refill "} ,
                { " Interjection " ,  " Emotion " ,  " Comma " ,  " Exclamation ",  " Point " ,  " Question "} ,
                { " Camping " ,  " Tents " ,  " Hiking " ,  " Mountains ",  " Fires " ,  " Fishing "} ,
                { " Overweight " ,  " Fat " ,  " Diet " ,  " Large ",  " Eat " ,  " Too "} ,
                { " Bugs " ,  " Mosquitos " ,  " Insects " ,  " Fly ",  " Wasps " ,  " Spray "} ,
                { " Augmentation " ,  " Enlarge " ,  " Escalate " ,  " Multiply ",  " Rise " ,  " Swell "} ,
                { " Octopus " ,  " Slippery " ,  " Ocean " ,  " Sea ",  " Animal " ,  " Soft "} ,
                { " Connection " ,  " Games " ,  " Music " ,  " Entertainment ",  " Downloads " ,  " Chatting "} ,
                { " Bouncer " ,  " Ball " ,  " Cricket " ,  " Bowler ",  " Disco " ,  " Batsman "} ,
                { " LCD" ,  " Liquid " ,  " Display " ,  " Computer ",  " Monitor " ,  " Crystal "} ,
                { " Velvet " ,  " Rabbit " ,  " Dress " ,  " Cloth ",  " Color " ,  " Soft "} ,
                { " Spigot " ,  " Sink " ,  " Faucet " ,  " Water ",  " Hose " ,  " Spray "} ,
                { " Lorry " ,  " Big " ,  " Freight " ,  " Wagon ",  " Truck " ,  " Vehicle"} ,
                { " Duvet " ,  " Soft " ,  " Warm " ,  " Bed ",  " Large " ,  " Sleep "}
        };
                return allwords;





        }
    }
