package com.secretbiology.taboo.words;

//This set was modified from following websites :
// (1) http://taboogame.net/ and Manually curated

public class WordSet2 {

    public String[][] words() {
        String[][] allwords = {

                {" Smile ", " Laugh ", " Drunk ", " Sad ", " Happy ", " Emotions "},
                {" Alabama ", " Southern ", " Yellowhammer ", " Mississippi ", " Montgomery ", " Georgia "},
                {" Testimony ", " Proof ", " Evidence ", " Validation ", " Verification ", " Testament "},
                {" Inflame ", " Inspire ", " Instigate ", " Motivate ", " Move ", " Pique "},
                {" Foolish ", " Absurd ", " Moronic ", " Idiotic ", " Mad ", " Silly "},
                {" Critic ", " Carper ", " Caviler ", " Harper ", " Nitpicker ", " Quibbler "},
                {" Boogers ", " Nose ", " Snot ", " Picking ", " Gooey ", " Green "},
                {" Triceps ", " Muscle ", " Bicep ", " Arm ", " Body ", " Lift "},
                {" Sleep ", " Deep ", " Rest ", " Snooze ", " Dream ", " Awaken "},
                {" Graveyard ", " Cemetery ", " Sacry ", " Grave ", " Dead ", " Death "},
                {" Mankind ", " Humanity ", " Race ", " God ", " World ", " Person "},
                {" Cyclops ", " Eye ", " Giant ", " Greek ", " Mythology ", " Poseidon "},
                {" Radiator ", " Heat ", " Metal ", " Steam ", " Winter ", " White (Sometimes) "},
                {" Fast ", " Team ", " Amazing ", " Wonderful ", " The Best ", " Taboo Champs "},
                {" Yearbook ", " Class ", " School ", " Photos ", " Autograph ", " Sign "},
                {" PC ", " Hard Disk ", " Computer ", " Mother Board ", " Apple ", " Windows "},
                {" Kenya ", " Masai Mara ", " Africa ", " Black ", " Athletes ", " Animals "},
                {" Byte ", " Memory ", " Chew ", " Teeth ", " Bit ", " Computer "},
                {" Frame ", " Picture ", " Photo ", " Display ", " Glasses ", " Around "},
                {" Plate ", " Circle ", " Eat ", " Food ", " Hold ", " Table "},
                {" Liquids ", " Milk ", " Water ", " Grease ", " Coffee ", " Blood "},
                {" Nile ", " River ", " Longest ", " Egypt ", " World Record ", " Africa "},
                {" Elevator ", " Lift ", " Building ", " Floor ", " Level ", " Apartment "},
                {" Gobble ", " Turkey ", " Thanksgiving ", " Leg ", " Dark ", " Meat "},
                {" Prefer ", " Like ", " Choice ", " Alternative ", " Want ", " Favour "},
                {" Adjacent ", " Close ", " Near ", " Proximate ", " Nigh ", " Immediate "},
                {" Lodge ", " Embed ", " Entrench ", " Fasten ", " Fix ", " Root "},
                {" Blender ", " Drink ", " Loud ", " Electric ", " Mix ", " Ice "},
                {" Apocalypse ", " X-Men ", " Time Traveler ", " Marvel ", " Comics ", " Beam & Omnipotent "},
                {" Equity ", " Owns ", " Portion ", " Fair ", " Stake ", " Impartial "},
                {" Amount ", " Aggregate ", " Total ", " Number ", " Reach ", " Final "},
                {" Insects ", " Fly ", " Aunt ", " Worms ", " Mosquito ", " Scorpion "},
                {" Demigod ", " Human ", " Hercules ", " Half ", " Son ", " Mortal "},
                {" Baseball ", " Home ", " Out ", " Base ", " Coach ", " Pitch "},
                {" Analysis ", " Examination ", " Review ", " Inspection ", " Investigation ", " Survey "},
                {" Toilet ", " Flush ", " Paper ", " Poop ", " Pee ", " Plumb "},
                {" Ease ", " Casual ", " Natural ", " Spontaneous ", " Effortless ", " Relax "},
                {" Italy ", " Leaning Tower ", " Rome ", " Venice ", " Leonardo De Vinci ", " Pizza "},
                {" Helipad ", " Helicopter ", " Airplane ", " Takeoff ", " Landing ", " Depart "},
                {" Speaking ", " Public ", " Talk ", " Speech ", " Universal ", " Mouth "},
                {" Firm ", " Organization ", " Business ", " Shared ", " Public ", " Corporation "},
                {" Cabin ", " Lake ", " Cottage ", " Summer ", " Fun ", " Friends "},
                {" Damp ", " Wet ", " Water ", " Towel ", " Moist ", " Humid "},
                {" Augmentation ", " Enlarge ", " Escalate ", " Multiply ", " Rise ", " Swell "},
                {" Engross ", " Write ", " Indite ", " Inscribe ", " Produce ", " Create "},
                {" Music ", " Jazz ", " R & B ", " Soul ", " Rock ", " Metal "},
                {" Jumper ", " Movie ", " Teleport ", " Move ", " Movie ", " Actor "},
                {" Clairvoyant ", " Senses ", " Psychic ", " Telepathic ", " Spirit ", " Prediction "},
                {" Still ", " Not Moving ", " Static ", " Quiet ", " Silent ", " Peace "},
                {" Star ", " Twinkle ", " Sun ", " Big ", " Bright ", " Earth "},
                {" Stirrer ", " Long ", " Stick ", " Plastic ", " Mix ", " Coffee "},
                {" Grain ", " Food ", " Wheat ", " Grown ", " Field ", " Ingredient "},
                {" Dissemblance ", " Act ", " Disguise ", " Pretense ", " Sham ", " Show "},
                {" Spoon ", " Eat ", " Cereal ", " Bowl ", " Fork ", " Silverware "},
                {" Comedian ", " Funny ", " Stand ", " Up ", " Joke ", " Teller "},
                {" Club ", " DJ ", " Music ", " Dance ", " Night ", " Going Out "},
                {" Socks ", " Feet ", " Athletic ", " Dress ", " Coverings ", " Tube "},
                {" Wrestling ", " Fake ", " Professional ", " Scripted ", " Sport ", " Grappling "},
                {" Wardrobe ", " Clothes ", " Keep ", " Bedroom ", " Hang ", " Jacket "},
                {" Angels ", " Wings ", " Heaven ", " Devil ", " Light ", " God "},
                {" Skull ", " Night ", " Halloween ", " Skeleton ", " Tomb Stone ", " Head "},
                {" Ballerinas ", " Shoes ", " Ballet ", " Black Swan ", " Opera ", " Dance "},
                {" Detach ", " Abstract ", " Disassociate ", " Disengage ", " Withdraw ", " Remove "},
                {" Crack ", " Sleuth ", " Break ", " Drop ", " Glass ", " Fragile "},
                {" Pimp ", " Prostitute ", " Corner ", " Cane ", " Fur Coat ", " Hoes "},
                {" Lollies ", " Sweet ", " Dentist ", " Yummy ", " Hard ", " Sugary "},
                {" Pencils ", " Wood ", " Carbon ", " Write ", " Child ", " Sharp "},
                {" Conch ", " Shell ", " Beach ", " Spiral ", " Mollusk ", " Ocean "},
                {" Mattress ", " Cover ", " Sleep ", " Double ", " Bed ", " Night "},
                {" Bahamas ", " Ocean ", " Island ", " Black People ", " Conch ", " Atlantis "},
                {" Resplendent ", " Big ", " Building ", " Structure ", " Magnificent ", " Bank Of China "},
                {" Speak ", " Talk ", " Languages ", " Phone ", " Communication ", " Voice "},
                {" Foot ", " Toe ", " Sock ", " Shoe ", " Leg ", " Body "},
                {" Provoke ", " Prompt ", " Excite ", " Goad ", " Impel ", " Incite "},
                {" Visor ", " Hat ", " Golf ", " Sun ", " Wear ", " Head "},
                {" Drinks ", " Pepsi ", " Coke ", " Red Bull ", " Beer ", " Wine "},
                {" Legislation ", " Law ", " Parliament ", " Court ", " Legislature ", " Mandate "},
                {" New ", " Old ", " Create ", " Generate ", " Invent ", " Fresh "},
                {" Ernest ", " Perfect ", " Lover ", " Angel ", " You ", " Love "},
                {" Aussies ", " Beach ", " Sun ", " Island ", " Aborigines ", " Shrimp "},
                {" Sunday ", " Saturday ", " Sunday ", " Church ", " Relax ", " Pub "},
                {" Menthol ", " Mint ", " Cigarette ", " Candies ", " Bubble Gum ", " Pepper Mint "},
                {" Type ", " Keyboard ", " Keys ", " Typewriter ", " Female ", " Male "},
                {" Axe ", " Chop ", " Blade ", " Tool ", " Weapon ", " Sharp "},
                {" Chicago ", " Windy ", " City ", " Sears Tower ", " Lake ", " Michigan Avenue "},
                {" Sunflower ", " Seeds ", " Yellow ", " Tall ", " Large ", " Oil "},
                {" Brat ", " Spoiled ", " Rotten ", " Mean ", " Child ", " Rich "},
                {" Mustang ", " Car ", " Horse ", " Ford ", " Sports Car ", " Fast "},
                {" Pegasus ", " Wing ", " Horse ", " Medusa ", " Fly ", " Mythology "},
                {" Eyeliner ", " Eyes ", " Black ", " Colors ", " Make-Up ", " Face "},
                {" Resign ", " Quit ", " Leave ", " Demit ", " Surrender ", " Waive "},
                {" Were ", " Are ", " When ", " With ", " Your ", " One "},
                {" Nigeria ", " Country ", " Africa ", " Tribes ", " African-Americans ", " Monkeys "},
                {" Nikon ", " Camera ", " Picture ", " Photography ", " Develop ", " Lens "},
                {" Fares ", " Wheel ", " Paris ", " Chubby ", " Awful ", " Kuwait "},
                {" Muscle ", " Strength ", " Biceps ", " Guns ", " Bone ", " Protein "},
                {" Trousseau ", " Wedding ", " Bride ", " Gown ", " Tiara ", " Big Day "},
                {" Sister ", " Annoying ", " Companion ", " Family ", " Close ", " You "},
                {" Athletic ", " Run ", " Food ", " Homework ", " Money ", " Company "},
                {" Yogurt ", " Dairy ", " Breakfast ", " Granola ", " Pudding ", " Strawberry "},
                {" Feces ", " Scat ", " Shit ", " Poop ", " Dung ", " Excrement "},
                {" Verb ", " Action ", " Word ", " Noun ", " Predicate ", " Grammar "},
                {" Stationary ", " Moving ", " Still ", " Unmoving ", " Set ", " In Place "},
                {" Archaeology ", " Baulk Walls ", " Dig ", " Indiana Jones ", " Artefact ", " History "},
                {" Camouflage ", " Deer ", " Hunting ", " Hide ", " Green ", " Woods "},
                {" Trunk ", " Car ", " Elephant ", " Truck ", " Antique ", " Motorcycle "},
                {" Ass ", " Bottom ", " Rare ", " Body ", " Donkey ", " Hole "},
                {" Budgie ", " Bird ", " Pet ", " Animal ", " Parrot ", " Chirp "},
                {" Supervise ", " Boss ", " Overlook ", " Oversee ", " Direct ", " Manage "},
                {" Drugs ", " Cocaine ", " Heroin ", " Pot ", " Weed ", " High "},
                {" Blend ", " Merge ", " Combine ", " Unify ", " Fuse ", " Mingle "},
                {" Vulture ", " Turkey ", " Black ", " King ", " Griffon ", " Egyptians "},
                {" Cat ", " Run ", " Jump ", " Animal ", " All Over The World ", " Lion "},
                {" Monkeys ", " Banana ", " Brown ", " Mammal ", " Has Thumb ", " Animal "},
                {" Zealous ", " Keen ", " Love ", " Emotions ", " Mad ", " Ardent "},
                {" Incests ", " A Game ", " The Whole ", " Family ", " Can ", " Play "},
                {" Tangerine ", " Orange ", " Fruit ", " Orange ", " Sweet ", " Juice "},
                {" Maltese ", " White ", " Fluffy ", " Animal ", " Terrier ", " Cross "},
                {" Participate ", " Partake ", " Join In ", " Play With ", " Sharing ", " Worry "},
                {" Snowman ", " Carrot ", " Snow ", " Winter ", " Woman ", " Cold "},
                {" windows ", " Island ", " Greece ", " Paradise ", " Castle ", " Beaches "},
                {" Bangles ", " Round ", " Girls ", " Hand ", " Cosmetics ", " Glass "},
                {" Minotaur ", " Bull ", " Man ", " Greek ", " Mythology ", " Labyrinth "},
                {" Forswear ", " Yield ", " Cede ", " Demit ", " Surrender ", " Waive "},
                {" Archery ", " Bows ", " Arrows ", " Shoot ", " Hunt ", " Accuracy "},
                {" Bun ", " Bakery ", " Pastry ", " Eat ", " Sandwich ", " Snack "},
                {" Off ", " Holiday ", " Leave ", " Not Working ", " On ", " Cold "},
                {" Pollution ", " Smog ", " Contaminate ", " Hazardous ", " Garbage ", " Emissions "},
                {" Discontinuation ", " Stay ", " Check ", " Stoppage ", " Halt ", " Stop "},
                {" Electrodes ", " Anion ", " Cation ", " Anode ", " Cathode ", " Anode Mud "},
                {" Result ", " Ending ", " Afterward ", " Over ", " Test ", " Solution "},
                {" Solubility ", " Solute ", " Solvent ", " Solution ", " Dissolve ", " Mixture "},
                {" Strict ", " Teacher ", " Sir ", " Planning ", " School ", " College "},
                {" Quiz ", " Cheat ", " School ", " Test ", " Study ", " Exam "},
                {" Autumn ", " Fall ", " Orange And Yellow ", " Winter ", " Spring ", " Rustic "},
                {" Albanian ", " Banana ", " Vanilla ", " Chocolate ", " Carmel ", " Apple "},
                {" Missed ", " Call ", " Bus ", " Car ", " Van ", " Some One "},
                {" Grimoire ", " Magic ", " Spell ", " Book ", " Wizard ", " Tome "},
                {" Moo ", " Cow ", " Hamburger ", " Banana ", " Orange ", " Cactus "},
                {" Scab ", " Skin ", " Dry Blood ", " Injury ", " Band Aid ", " Fill In Worker "},
                {" Storm ", " Flood ", " Tornado ", " Tsunami ", " Rain ", " Wind "},
                {" Noose ", " Gallows ", " Hang ", " Neck ", " Rope ", " Tie "},
                {" Manicure ", " Hands ", " French ", " Salon ", " Nail ", " Pedicure "},
                {" Fall ", " Autumn ", " Trip ", " Descend ", " Accident ", " Season "},
                {" Diary ", " Girl ", " Pillow ", " Mother ", " Read ", " Personal "},
                {" Pet ", " Animal ", " Cat ", " Dog ", " House ", " Love "},
                {" Wrinkle ", " Old ", " Clothes ", " Face ", " Forehead ", " Iron "},
                {" Chimes ", " Bells ", " Window ", " Door ", " Church ", " Wind "},
                {" Same ", " Different ", " Opposite ", " Twins ", " Similar ", " Alike "},
                {" Heart ", " Pump ", " Blood ", " Circulate ", " Chambers ", " Brain "},
                {" Stingray ", " Steve Irwin ", " Flap ", " Ocean ", " Poison ", " Water "},
                {" Cyclone ", " Hurricane ", " Volcano ", " Wind ", " Disaster ", " Danger "},
                {" Wealthy ", " Rich ", " Bill Gates ", " Money ", " Dollars ", " Cash "},
                {" Congress ", " Failure ", " Slow ", " Deadlock ", " Laws ", " Scandal "},
                {" Flourescent ", " Colour ", " Bright ", " Neon ", " Glow ", " Light "},
                {" Smoothie ", " Blender ", " Fruit ", " Juice ", " Banana ", " Drink "},
                {" Exploration ", " Explore ", " Discover ", " See ", " Probe ", " Investigate "},
                {" Egg ", " Chicken ", " Poultry ", " Chick ", " Scramble ", " Food "},
                {" Grip ", " Grasp ", " Hold ", " Clasp ", " Clench ", " Clutch "},
                {" Elastic ", " Rubber ", " Stretch ", " Sew ", " Band ", " Return "},
                {" Behead ", " Decapitate ", " Chop Off Head ", " Headless ", " Guillotine ", " Block "},
                {" Food ", " Steak ", " Potato ", " Chicken ", " Corn ", " Candy "},
                {" We ", " Us ", " Our ", " Family ", " Group ", " Joint "},
                {" Brittle ", " Candy ", " Fragile ", " Peanut ", " Sweet ", " Delicate "},
                {" Example ", " E.G. ", " Paper , Exam ", " Explain ", " Make Understand ", " Ample "},
                {" Raspberry ", " Jam ", " Toast ", " Pie ", " Fruit ", " Furry "},
                {" Parallel ", " Lines ", " Together ", " Direction ", " Intersect ", " Opposite "},
                {" Mermaids ", " Tail ", " Scales ", " Long Hair ", " Dolphins ", " Merman "},
                {" Invention ", " Create ", " Patent ", " New ", " Useful ", " Share "},
                {" Ornament ", " Ball ", " Hang ", " Tree ", " Christmas ", " Decorate "},
                {" Greetings ", " Holla ", " Hello ", " Welcome ", " Cards ", " Goodnight "},
                {" Eggplant ", " Purple ", " Vegetable ", " Food ", " Edible ", " Cucumber "},
                {" Lollipop ", " Lick ", " Ice-cream ", " Lolly ", " Stick ", " Android "},
                {" Plateau ", " Mesa ", " Flat ", " Level ", " Mountain ", " Rock "},
                {" Unitary ", " One ", " Control ", " All ", " Total ", " Decision Making "},
                {" Cpu ", " Central ", " Brain ", " Mainframe ", " Programs ", " Calculation "},
                {" Win ", " Try ", " Best ", " Go ", " Hell ", " You "},
                {" Simpson ", " Cartoon ", " Bart ", " Homer ", " Television ", " Marge "},
                {" Stylist ", " Hair ", " Cut ", " Style ", " Professional ", " Career "},
                {" Clown ", " Potato-Nose ", " Curly Hair ", " Juggler ", " Circus ", " Chaplin "},
                {" Boring ", " Bored ", " Boredom ", " Math ", " Civics ", " Teachers "},
                {" Electron ", " Proton ", " Neutron ", " Atom ", " Magnetism ", " Negative "},
                {" Heels ", " Tall ", " Women ", " Fancy ", " Thin ", " Sandal "},
                {" Kidney ", " Urine ", " Waste ", " Excretory ", " Nephrons ", " Filter "},
                {" Ping ", " Ming ", " Short Message ", " Bingo ", " Mailing ", " Browse "},
                {" Fantasia ", " Mickey Mouse ", " Brooms ", " Wizard ", " Dinosaurs ", " Nanny "},
                {" Freedom ", " Ring ", " Choice ", " Democracy ", " America ", " Liberty "},
                {" Pose ", " Model ", " Photo ", " Magazine ", " Shoot ", " Famous "},
                {" Burger ", " Junk ", " Waste ", " Tasty ", " Ham ", " Hotdog "},
                {" Badge ", " Cops ", " Law ", " Rules ", " Ticket ", " Police "},
                {" Katie ", " Awesome ", " Pretty ", " Funny ", " Smart ", " Best "},
                {" Somber ", " Sad ", " Down ", " Depressed ", " Unhappy ", " Demoralized "},
                {" Partner ", " Share ", " Activity ", " Member ", " Relation ", " Fellow "},
                {" Raw ", " Meat ", " Uncooked ", " Vegetables ", " Emotion ", " Food "},
                {" Caution ", " Proceed ", " Yellow ", " Tape ", " Crime Scene ", " Police "},
                {" Clipboard ", " Rigid ", " Official ", " Coach ", " Paper ", " Holder "},
                {" Squash ", " Plant ", " Sport ", " Pumpkin ", " Eat ", " Crush "},
                {" Bird ", " Fly ", " Wings ", " Feather ", " Pigeons ", " Eggs "},
                {" Wild ", " Lion ", " Monster ", " Zoo ", " King ", " Life "},
                {" Timberland ", " Brand ", " Singer ", " Cloth ", " Footwear ", " Rangers "},
                {" Spleen ", " Body ", " Organ ", " Abdomen ", " Rupture ", " Remove "},
                {" Dominoes ", " Pizza ", " Take Away ", " Game ", " Cheese ", " Italian "},
                {" Heated ", " Heat ", " Hot ", " Past Tense ", " Fire ", " Warm "},
                {" Ivory ", " Elephant ", " Coast ", " Piano ", " White ", " Africa "},
                {" Cafeteria ", " Food ", " Lunch ", " Self Serve ", " Office ", " School "},
                {" Oysters ", " Shuck ", " Half Shell ", " Pearl ", " Aphrodisiac ", " Raw "},
                {" Sisters ", " Female ", " Sibling ", " Related ", " Family ", " Girls "},
                {" Increase ", " Forward ", " More ", " Size ", " Decrease ", " Backward "},
                {" Coin ", " Zeppelin ", " Road ", " Trees ", " Earth ", " Eris "},
                {" Hamburger ", " Ground ", " Food ", " Bun ", " Patty ", " Beef "},
                {" Badminton ", " Racket ", " Court ", " Grip ", " Shoes ", " Partner "},
                {" Croissant ", " Butter ", " Pastry ", " France ", " Almond ", " Breakfast "},
                {" Randomness ", " Unexpected ", " Weird ", " Off-Topic ", " Odd ", " Inconsistent "},
                {" Ethics ", " Honest ", " Money ", " Interest ", " Integrity ", " Lying "},
                {" Spirit ", " Ghost ", " Poltergeist ", " Shade ", " Dead ", " Sense "},
                {" Pump ", " Pressure ", " Enlarge ", " Water ", " Breast ", " Stomach "},
                {" Cats ", " Tiger ", " Scratch ", " Colored ", " Animal ", " Lovely "},
                {" Marriage ", " Anniversary ", " Adoption ", " Baby ", " Bride ", " Shopping "},
                {" Bully ", " Harass ", " Strong ", " Pick On ", " School ", " Peer "},
                {" Prism ", " Geo ", " Light ", " Rainbow ", " Refract ", " Pink Floyd "},
                {" Typo ", " Keyboard ", " Button ", " Computer ", " Fingers ", " Clumsy "},
                {" Rosemary ", " Herb ", " Spice ", " Name ", " Flower ", " Thyme "},
                {" Flow ", " Move ", " Water ", " Free ", " Pass ", " Hold "},
                {" Swan ", " Bird ", " White ", " Fly ", " Wings ", " Beautiful "},
                {" Pig ", " Feet ", " Nose ", " Sty ", " Dirty ", " Pink "},
                {" Penny ", " Cent ", " Loafer ", " Candy ", " Copper ", " Bank "},
                {" Steeple ", " Church ", " Tall ", " Cross ", " Doors ", " Tower "},
                {" Gimmick ", " Deception ", " Trick ", " Subterfuge ", " Wile ", " Ploy "},
                {" Communism ", " China ", " Russia ", " Native ", " Sickle ", " Red "},
                {" Closet ", " Clothes ", " Hang ", " Bedroom ", " Store ", " Monster "},
                {" Summit ", " Eagle ", " Mountain ", " Cold ", " Snow ", " Top "},
                {" Crackers ", " White ", " Racist ", " European ", " Smelly ", " Pale "},
                {" United ", " Airlines ", " States ", " Arms ", " Nations ", " Press "},
                {" Princeton ", " University ", " Study ", " Tough ", " President ", " Admission "},
                {" Jog ", " Run ", " Walk ", " Fast ", " Morning ", " Path "},
                {" Geography ", " Subject ", " World ", " Map ", " Population ", " Weather "},
                {" Calender ", " Dates ", " Days ", " Months ", " Year ", " Holidays "},
                {" Brown ", " University ", " Bear ", " Dan ", " County ", " Hotel "},
                {" Lion ", " Cat ", " Big ", " Wild ", " Brave ", " Strong "},
                {" Province ", " Area ", " Domain ", " Orbit ", " Field ", " Realm "},
                {" Easter ", " Eggs ", " Rabbit ", " Basket ", " Chocolate ", " Hiding "},
                {" Tarantula ", " Big ", " Spider ", " Legs ", " Bite ", " Bath "},
                {" Cranium ", " Board Game ", " Brain ", " Head ", " Think ", " Skull "},
                {" Dismiss ", " Release ", " Discharge ", " Drop ", " Terminate ", " Cashier "},
                {" Sombrero ", " Hat ", " Mexican ", " Straw ", " Colorful ", " Round "},
                {" Viper ", " Poison Sting ", " Neurotoxin ", " Viper Strike ", " Corrosive Skin ", " Orb Walk "},
                {" Terrorism ", " Terrorist ", " Bombs ", " Deaths ", " Hostages ", " Victims "},
                {" Hungary ", " Budapest ", " Europe ", " Goulash ", " Danube ", " Wine "},
                {" Tigers ", " Stained ", " Clean ", " Dirty ", " Fast ", " Slow "},
                {" Benefit ", " Salary ", " Pension ", " Vacation ", " Incentive ", " Uniform "},
                {" Ammunition ", " Gun ", " War ", " Soldier ", " Fight ", " Bullets "},
                {" Espresso ", " Italian ", " Colombian ", " Demitasse ", " Coffee ", " Strong "},
                {" Mac ", " Apple ", " Big ", " Mcdonald ", " Steve Jobs ", " Pc "},
                {" Decimal ", " Point ", " Zero ", " Numbers ", " Maths ", " Algebra "},
                {" Giant ", " Andre ", " Beanstalk ", " Tall ", " Person ", " Mythical "},
                {" Lions ", " Animal ", " Africa ", " Strong ", " Mane ", " Paw "},
                {" Babysitter ", " Infant ", " Child ", " Toddler ", " Kid ", " Teenager "},
                {" Acid ", " Rain ", " Clean ", " Hcl ", " Science ", " Chemistry "},
                {" Museum ", " Art ", " Science ", " History ", " Artifacts ", " Display "},
                {" Ginseng ", " Chinese ", " Herb ", " Roots ", " Tea ", " Chicken "},
                {" Geisha ", " Japan ", " Entertainment ", " Women ", " Kimono ", " Dance "},
                {" Economy ", " Money ", " Debt ", " Trade ", " Import ", " Export "},
                {" Surround ", " Sound ", " Speakers ", " Around ", " Gather ", " Circle "},
                {" Angel ", " Heaven ", " Wings ", " White ", " Glow ", " Watch "},
                {" Launchpad ", " Computer ", " Apple ", " Applications ", " Icons ", " Services "},
                {" Binder ", " Mitt Romney ", " Women ", " School ", " Notebook ", " Paper "},
                {" Symbol ", " Swastika ", " Egypt ", " Ancient ", " Runes ", " Teams "},
                {" Singapore ", " Unique ", " Lion ", " Multi-Racial ", " Idol ", " Chinese, Indian & Malay "},
                {" Marijuana ", " Weed ", " Gras ", " Mary ", " Jane ", " Joint "},
                {" Safe ", " Sure ", " Danger ", " Secure ", " Protected ", " Save "},
                {" Gorilla ", " Monkey ", " Big ", " Ape ", " Jungle ", " King Kong "},
                {" Capitalism ", " Money ", " Economic ", " System ", " Market ", " Commerce "},
                {" Accident ", " Car ", " Vehicle ", " Crash ", " Collision ", " Damage "},
                {" Plane ", " Flight ", " Transportation ", " Pilot ", " Sky ", " Hostess "},
                {" Hit ", " Strike ", " Press ", " Key ", " Target ", " Attack "},
                {" Trouble ", " Problems ", " Misbehaves ", " Not As Planned ", " Bad ", " Emotional "},
                {" Kongo ", " Water ", " River ", " Big ", " Africa ", " Kingdom "},
                {" Umpire ", " Baseball ", " Pitcher ", " Catcher ", " Glove ", " Referee "},
                {" Cleavage ", " Boobs ", " Tits ", " Big ", " Visible ", " Seen "},
                {" Officer ", " Post ", " Police ", " Guard ", " Office ", " Desk "},
                {" Mouth ", " Talk ", " Tung ", " Teeth ", " Gums ", " Lost "},
                {" Pug ", " Dog ", " Face ", " Breed ", " Small ", " Cute "},
                {" Sides ", " East ", " West ", " North ", " South ", " West North "},
                {" Closure ", " Lock ", " Shutting ", " Occlusion ", " Stop ", " Halt "},
                {" Divorce ", " Court ", " Relationship ", " Pain ", " Money ", " Lawyer "},
                {" This ", " That ", " Word ", " Not ", " Pronoun ", " What "},
                {" Martini ", " Olive ", " Apple ", " Dirty ", " Rocks ", " Fruity "},
                {" Chain ", " Mail ", " Letter ", " Restaurant ", " Link ", " Metal "},
                {" Spelunking ", " Cave ", " Explore ", " Head Lamp ", " Underground ", " Dark "},
                {" True ", " Honest ", " False ", " Right ", " Accurate ", " Genuine "},
                {" Breadwinner ", " Money ", " Works ", " Hard ", " Payday ", " Collects "},
                {" Strawberry ", " Red ", " Plant ", " California ", " Milk Shake ", " Beatles "},
                {" Function ", " Job ", " Purpose ", " Role ", " Task ", " Perform "},
                {" Fit ", " Sexy ", " Cute ", " Beauty ", " Good Looking ", " Thin "},
                {" Derivative ", " Function ", " Limit ", " Slope ", " Differentiate ", " Change "},
                {" Nest ", " Bird ", " Egg ", " Tree ", " Fly ", " Bird Breeds "},
                {" Seashell ", " Beach ", " Sand ", " Necklace ", " Ocean ", " Crab "},
                {" Reality ", " Original ", " Artificial (Not) ", " Fake ", " Fact ", " Proof "},
                {" Chest ", " Heart ", " Beat ", " Blood ", " Broken ", " Love "},
                {" Imagine ", " Conceive ", " Envision ", " Image ", " See ", " Think "},
                {" Mushroom ", " Fungus ", " Super Mario ", " Ground ", " Pot ", " Pizza "},
                {" Key ", " House ", " Car ", " Boat ", " Safe ", " Smith "},
                {" Golf ", " Eagle ", " Club ", " Green ", " Cart ", " Birdie "},
                {" Microwave ", " Cooking ", " Food ", " Defrost ", " Baking ", " Heating "},
                {" Tonsil ", " Surgery ", " Adenoids ", " Kids ", " Infection ", " Throat "},
                {" Winter ", " Season ", " Christmas ", " Snow ", " December ", " Cold "},
                {" Sports ", " Football ", " Baseball ", " Basketball ", " Soccer ", " Rugby "},
                {" Mit ", " University ", " Engineering ", " Private ", " Prestigious ", " Rigorous "},
                {" Bone ", " Break ", " Cast ", " Boot ", " Heal ", " Body "},
                {" Consistent ", " Steady ", " Reliable ", " Constant ", " Regular ", " Inconsistent "},
                {" Cloak ", " Cape ", " Shawl ", " Invisibility ", " Cold ", " Costume "},
                {" Crusades ", " Murder ", " Killing ", " Christianity ", " Hate ", " Genocide "},
                {" Teeth ", " Mouth ", " Gums ", " Toothbrush ", " Floss ", " Dentures "},
                {" Ancestor ", " Forefather ", " Foremother ", " Ascendant ", " Parent ", " Predecessor "},
                {" Justice ", " A Store ", " Court ", " Fair ", " Comic ", " Marvel "},
                {" Hangar ", " Stay ", " Hip ", " Tiger ", " Jump ", " Cook "},
                {" Fogey ", " Old ", " Man ", " Dodo ", " Fossil ", " Ancient "},
                {" Collar ", " Dog ", " Shirt ", " Horse ", " Neck ", " Nab "},
                {" Oranges ", " Color ", " Citrus ", " Lemon ", " Fruit ", " Apple "},
                {" Snickers ", " Chocolate ", " Caramel ", " Nuts ", " Bar ", " Candy "},
                {" Accountant ", " Ledger ", " Invoices ", " Vouchers ", " Balance ", " Debit Credit "},
                {" Ariel ", " Little ", " Mermaid ", " Disney ", " Sea ", " World "},
                {" Trojans ", " Southern ", " California ", " Mascot ", " Horse ", " Champions "},
                {" Stock ", " Shares ", " Company ", " Loss ", " Profit ", " Mutual "},
                {" Zombie ", " Dead ", " Eat ", " Flesh ", " Alive ", " Resurrection "},
                {" Freeway ", " Cars ", " Fast ", " Trucks ", " Carpool ", " Transportation "},
                {" Teenager ", " School ", " Ten ", " Kids ", " Grow ", " Fight "},
                {" Duct ", " Air ", " Metal ", " Hollow ", " Heat ", " Ac "},
                {" Chip ", " Chocolate ", " Potato ", " Shoulder ", " Block ", " Wood "},
                {" Sombre ", " Gloomy ", " Shady ", " Dark ", " Dull ", " Umbra "},
                {" Footstool ", " Ottoman ", " Rest ", " Furniture ", " Cushion ", " Couch "},
                {" Superman ", " Spiderman ", " Phantom ", " Diana ", " Ladies ", " Amazing "},
                {" Scrupulous ", " Careful ", " Fastidious ", " Meticulous ", " Painstaking ", " Attentiveness "},
                {" Antlers ", " Deer ", " Bucks ", " Moose ", " Fighting ", " Mates "},
                {" Faucet ", " Water ", " Sink ", " Spout ", " Leak ", " Handle "},
                {" Hybrid ", " Werewolf ", " Vampire ", " Blood ", " Transformation ", " Both "},
                {" Plummeted ", " Plunge ", " Decline ", " Decrease ", " Down ", " Crash "},
                {" Brotherhood ", " Group ", " Common ", " Believe ", " Ideals ", " Principles "},
                {" Snapback ", " Hat ", " Adjustable ", " Obey ", " New Era ", " Fitted "},
                {" Insufflate ", " Snort ", " Nose ", " Sniff ", " Drugs ", " Administration "},
                {" Gym ", " Weights ", " Dumb Bells ", " Sweat ", " Muscles ", " Workout "},
                {" Protein ", " Muscle ", " Meat ", " Bones ", " Nutrient ", " Nuts "},
                {" Moist ", " Wet ", " Humid ", " Water ", " Cream ", " Sweat "},
                {" Basketball ", " Court ", " Bounce ", " Foul ", " Hoop ", " Net "},
                {" Escalator ", " Up ", " Steps ", " Mall ", " Lift ", " Walk "},
                {" Galaxy ", " Sun ", " System ", " Space ", " Earth ", " Milky Way "},
                {" Ulcer ", " Acid ", " Hemorrhage ", " Blood ", " Gastric ", " Stomach "},
                {" Cuba ", " Island ", " Nation ", " Refugees ", " Communist ", " Cigars "},
                {" Metals ", " Gold ", " Silver ", " Iron ", " Zinc ", " Bronze "},
                {" Mailman ", " Job ", " Letter ", " Box ", " House ", " Package "},
                {" Athena ", " Greece ", " Goddess ", " War ", " Wisdom ", " Zeus "},
                {" Dove ", " Peace ", " White ", " Bird ", " Olive ", " Freedom "},
                {" Ostrich ", " Quick ", " Meat ", " Bird ", " Land ", " Egg "},
                {" Sanitizer ", " Clean ", " Liquid ", " Hands ", " Cold ", " Flasks "},
                {" Region ", " District ", " Locality ", " Council Area ", " Local Council ", " Planning "},
                {" Maggot ", " Larvae ", " Fly ", " Dead ", " White ", " Bug "},
                {" Investment ", " Return ", " Interest ", " Money ", " Deposit ", " Cash "},
                {" Indonesia ", " Polluted ", " Jakarta ", " Asian Country ", " Bali ", " East Timor "},
                {" Saree ", " Women ", " Indian ", " Wear ", " Clothes ", " Long "},
                {" Government ", " Judicial ", " Legislative ", " Branch ", " Executive ", " Power "},
                {" See ", " Ships ", " Fishes ", " Sailing ", " Boating ", " Yacht "},
                {" Jail ", " Broken ", " Cell ", " Laws ", " Bars ", " Inmate "},
                {" Turtle ", " Green ", " Shell ", " Sea ", " Reptile ", " Animal "},
                {" Marshmallow ", " Sticky ", " Camp ", " Stick ", " Food ", " Android "},
                {" Ambulance ", " Siren ", " White ", " Hospital ", " Vehicle ", " Emergency "},
                {" Stripper ", " Pole ", " Club ", " Dollar Bills ", " Pimps ", " Trashy "},
                {" Housewife ", " Wife ", " House ", " Stays ", " Home ", " Midwife "},
                {" Flora ", " Plant ", " Scientific ", " Fauna ", " Tree ", " Flower "},
                {" Cooper ", " Padre ", " Murphy ", " Bartender ", " Coworker ", " Quiet "},
                {" Harbinger ", " Omen ", " Presage ", " Prediction ", " Augury ", " Prophesy "},
                {" Mural ", " Picture ", " Painting ", " Wall ", " Famous ", " Landscape "},
                {" Poster ", " Paper ", " Flat ", " Thin ", " Wall ", " Room "},
                {" Modulate ", " Change ", " Key ", " Different ", " Adjust ", " Alter "},
                {" April ", " Spring ", " Flowers ", " Growth ", " Bright Colors ", " After March "},
                {" Darts ", " Board ", " Target ", " Throw ", " Game ", " Bar "},
                {" Simple ", " Easy ", " Quick ", " Complicated ", " Fast ", " Small "},
                {" Cemetery ", " Grave Yard ", " Dead ", " Tomb ", " Mausoleum ", " Funeral "},
                {" Undead ", " Vampire ", " Zombie ", " Horde ", " Left For Dead ", " George A Romero "},
                {" Her ", " Girl ", " She ", " Female ", " Wife ", " Woman "},
                {" Pinwheel ", " Wind ", " Toy ", " Spiral ", " Spin ", " Blow "},
                {" Subterfuge ", " Artifice ", " Device ", " Deception ", " Dodge ", " Wile "},
                {" Fun ", " Enjoyable ", " Leisurely ", " Great ", " Hobby ", " Laughter "},
                {" Moustache ", " Beard ", " Mouth ", " Lip ", " Face ", " Hair "},
                {" Fan ", " Device ", " Wings ", " Air ", " Cooling ", " Waving "},
                {" Wife ", " Legal ", " Lover ", " Female ", " Married ", " Woman "},
                {" Shelter ", " Home ", " Hospice ", " Hospital ", " Asylum ", " Institution "},
                {" World ", " House ", " Sky ", " Earth ", " Yards ", " Trees "},
                {" Corkscrew ", " Open ", " Bottle ", " Twist ", " Spiral ", " Turn "},
                {" Later ", " After ", " Next ", " Coming ", " Latterly ", " After Wards "},
                {" Planking ", " Lay ", " Public ", " Picture ", " Arms ", " Head "},
                {" Safari ", " Wild Life ", " Trees ", " Journey ", " Africa ", " Tracker "},
                {" Relaxed ", " Calm ", " Breath ", " Restful ", " Peaceful ", " Tranquil "},
                {" Retract ", " Abjure ", " Recall ", " Recant ", " Withdraw ", " Take Back "},
                {" Knifes ", " Cut ", " Scratch ", " Blood ", " Blade ", " Sharp "},
                {" Remember ", " Forget ", " Titans ", " Alamo ", " Brain ", " Retain "},
                {" Particles ", " Atom ", " Everything ", " Science ", " Make ", " Universe "},
                {" Lunch ", " Eat ", " Break ", " School ", " Work ", " Noon "},
                {" Swap ", " Hedge ", " Interest Rate ", " Trade ", " Risk ", " Exchange "},
                {" Twilight ", " Vampire ", " Sun ", " Night ", " Edward ", " Bella "},
                {" Rats ", " Rodents ", " Evil ", " Dark ", " Tails ", " Kitchen "},
                {" Raclette ", " Cheese ", " Potatoes ", " Winter ", " Switzerland ", " Food "},
                {" Unimpeded ", " Open ", " Clear ", " Free ", " Unblocked ", " Unobstructed "},
                {" What ", " How ", " Why ", " Where ", " Who ", " That "},
                {" Plants ", " Green ", " Nature ", " Animals ", " Flowers ", " Fruits "},
                {" Coal ", " Black ", " Power ", " Vehicle ", " Mines ", " India "},
                {" Immediate ", " Instant ", " Fast ", " Prompt ", " Quick ", " Urgent "},
                {" Eagle ", " Beak ", " Wing ", " Eyes ", " Animal ", " Long Tree "},
                {" Winchester ", " Rifle ", " Pistol ", " Shoot ", " Bullets ", " Shotgun "},
                {" Game ", " Play ", " Competition ", " Cricket ", " Computer ", " Win "},
                {" Chair ", " Sit ", " Down ", " Floor ", " Table ", " Legs "},
                {" Censor ", " Ban ", " Black Out ", " Hush ", " Stifle ", " Suppress "},
                {" Cracker ", " Cheese ", " Biscuit ", " Food ", " Christmas ", " Cream "},
                {" Guano ", " Bird ", " Bat ", " Poop ", " White ", " Cave "},
                {" Spice ", " Strong ", " Curry ", " Kitchen ", " Aroma T ", " Order "},
                {" Mortgage ", " Own ", " Loan ", " Debt ", " Home ", " Rent "},
                {" Wholly ", " All ", " Completely ", " Altogether ", " Totally ", " Just "},
                {" Korea ", " South ", " North ", " Asia ", " Japan ", " Country "},
                {" Miami ", " South Beach ", " Night Clubs ", " Cubans ", " Florida ", " Hispanics "},
                {" Right ", " Pencil ", " Left ", " Paper ", " Hand ", " Wrong "},
                {" Charger ", " Cell Phone ", " Electrical ", " Connection ", " Outlet ", " Bars "},
                {" Netherlands ", " Europe ", " Tulips ", " Windmill ", " Dutch ", " Wooden Shoes "},
                {" Vibrate ", " Cell ", " Phone ", " Mobile ", " Ring ", " Call "},
                {" Flipflop ", " Water ", " Sandal ", " Comfortable ", " On Everyone ", " Feet "},
                {" Outstanding ", " Topnotch ", " Excellent ", " Wow Factor ", " Highest ", " Best "},
                {" Divine ", " God ", " Music ", " Spiritual ", " Bless ", " Yoga "},
                {" Project ", " Project Manager ", " Funding ", " Budget ", " Scope ", " Architect "},
                {" Affinity ", " Attraction ", " Yesterday ", " Natural ", " Vocabulary ", " Have "},
                {" Wig ", " Head ", " Wear ", " Top ", " Long ", " Hair "},
                {" Cigarette ", " Smoke ", " Quit ", " Filter ", " Pack ", " Carton "},
                {" Tv ", " Heroes ", " Lost ", " Desperate Housewives ", " The Oc ", " Csi "},
                {" Phantom ", " Opera ", " Mask ", " Christine ", " Scary ", " Ghost "},
                {" Parent ", " Love ", " Guardian ", " Birth ", " Mother ", " Father "},
                {" Sex ", " Pleasure ", " Fun ", " Fast ", " Bed ", " Loud "},
                {" Column ", " Line ", " File ", " Rank ", " Row ", " Tier "},
                {" Transparent ", " Solid ", " Substance ", " Container ", " Glassware ", " Glass "},
                {" Minutes ", " Time ", " Hour ", " Seconds ", " Days ", " Weeks "},
                {" Heavens ", " God ", " Nice ", " Everything ", " Sky ", " High "},
                {" Fist ", " Hand ", " Fingers ", " Punch ", " No ", " Actions "},
                {" Silence ", " Quiet ", " Dead ", " Speeches ", " Noisy ", " Calm "},
                {" Ceramic ", " Pot ", " Clay ", " Art ", " Kiln ", " Wheel "},
                {" Widower ", " Husband ", " Wife ", " Man ", " Dead ", " Sky "},
                {" Temple ", " God ", " Worship ", " Mosque ", " Church ", " Ram "},
                {" Orthodox ", " Christian ", " Serbia ", " Greece ", " Religion ", " Russia "},
                {" Bottles ", " Beer ", " Drink ", " Glass ", " Broken ", " Liquid "},
                {" Mercury ", " Thermometer ", " God ", " Planet ", " Queen ", " Morris "},
                {" Party ", " Celebrate ", " Birthday ", " New Years ", " Fun ", " Weekend "},
                {" Shoelace ", " Tie ", " String ", " Belt ", " Tighten ", " Colorful "},
                {" Bedroom ", " Sleep ", " Bed ", " Rest ", " Mattress ", " Cover "},
                {" Own ", " My ", " Mine ", " Me ", " Owned ", " Myself "},
                {" Football ", " Spike ", " Throw ", " Catch ", " Kick ", " Score "},
                {" Hemoglobin ", " Iron ", " Cell ", " Red ", " Anatomy ", " Blood "},
                {" Bridge ", " Card Game ", " Water ", " Connects ", " River ", " Cross "},
                {" Yard ", " Trees ", " House ", " Cars ", " Garage ", " Grass "},
                {" Agree ", " Accord ", " Check ", " Chime ", " Correspond ", " Match "},
                {" Gong ", " Round ", " Metal ", " Hit ", " Bong ", " Sound "},
                {" Revise ", " Wise ", " Revision ", " Exam ", " Hall ", " School "},
                {" Testify ", " Attest ", " Validate ", " Back ", " Warrant ", " Justify "},
                {" Witches ", " Charmed ", " Supernatural ", " Magic ", " Spells ", " Potions "},
                {" Sincerely ", " Frankly ", " Letter ", " Sign-Off ", " Truly ", " Candidly "},
                {" Grazing ", " Cattle ", " Sheep ", " Cows ", " Grass ", " Eat "},
                {" Pitcher ", " Jug ", " Baseball ", " Water ", " Throw ", " Pour "},
                {" Nightingale ", " Ninja ", " Assassin ", " Across ", " Birds ", " Floor "},
                {" Orphan ", " Orphanage ", " Poor ", " Kids ", " Food ", " Injured "},
                {" Report ", " Book ", " Above ", " Manager ", " Summary ", " Speak "},
                {" Chocolate ", " Cocoa ", " Sweet ", " Special Occasion ", " Shapes ", " Belgium "},
                {" Suspicious ", " Doubting ", " Trust ", " Uncertain ", " Paranoid ", " Usual "},
                {" Squirt ", " Movie ", " Squeeze ", " Come ", " Fun ", " Teen "},
                {" Scorpion ", " King ", " Tail ", " Bite ", " Stings ", " Fish "},
                {" Sun ", " Room ", " Glasses ", " Shine ", " Rise ", " Astronomy "},
                {" Plaster ", " Wall ", " Bandage ", " First Aid ", " Cover ", " Cut "},
                {" Hose ", " Pouch ", " Gallop ", " Animal ", " Australia ", " Captain "},
                {" Frighten ", " Alarm ", " Panic ", " Scare ", " Startle ", " Terrify "},
                {" Whistle ", " Blow ", " Sound ", " Referee ", " Mouth ", " High Pitch "},
                {" Handkerchief ", " Nose ", " Cloth ", " Pocket ", " Wipe ", " Tissue "},
                {" Headlight ", " Deer ", " Car ", " Light ", " Night ", " Drive "},
                {" Narcotic ", " Recreational ", " Illegal ", " Drug ", " Substance ", " High "},
                {" Ponytail ", " Hair Tye ", " Hair ", " Pony ", " Style ", " Bald "},
                {" Prince ", " Royal ", " Family ", " England ", " Boy ", " Male "},
                {" Deliver ", " Give ", " Supply ", " Provide ", " Transfer ", " Hand "},
                {" Daisy ", " Blonde ", " Blue-Eyed ", " Great Gatsby ", " Girl ", " Love Interest "},
                {" Substitute ", " Teacher ", " Replacement ", " Exchange ", " Alternate ", " Accept "},
                {" Demean ", " Deport ", " Do ", " Quit ", " Carry ", " Bare "},
                {" Diet ", " Sugar Free ", " Loss ", " Weight ", " Resolution ", " Scale "},
                {" Squeak ", " Mouse ", " Rust ", " Gate ", " Oil ", " Grease "},
                {" Thor ", " Hammer ", " Norse ", " God ", " Judgement ", " Mythology "},
                {" Hindi ", " India ", " Language ", " Speak ", " Sanskrit ", " Country "},
                {" Bills ", " Telephone ", " Duck ", " Utility ", " Checks ", " Pay "},
                {" Shirt ", " Round And V Neck ", " Wear ", " Clothes ", " Informal ", " Summer Wear "},
                {" Blockbuster ", " Video Store ", " Movies ", " Games ", " Successful ", " Production "},
                {" Gut ", " Intestine ", " Digestion ", " Courage ", " Eat ", " Stomach "},
                {" Subsequent ", " Next ", " Follow ", " After ", " Order ", " Then "},
                {" Cashier ", " Money ", " Teller ", " Bank ", " Credit ", " Food "},
                {" Sentence ", " Words ", " Full Stop ", " Capital Letter ", " Long Or Short ", " Writing "},
                {" Advertising ", " Agency ", " Commercial ", " Print ", " Brand ", " Tv "},
                {" Date ", " Day ", " Month ", " Period ", " Romantic Appointment ", " Year "},
                {" Lisbon ", " Hills ", " Portugal ", " Sunny ", " Capital ", " Tram "},
                {" Oath ", " Promise ", " Swear ", " Take ", " Vow ", " Pledge "},
                {" Calypso ", " Caribbean ", " Song ", " Mighty Sparrow ", " Island ", " Genre "},
                {" Publicize ", " Promote ", " Boost ", " Enhance ", " Puff ", " Tout "},
                {" Blinds ", " Venetian ", " Curtains ", " Window ", " String ", " Cover "}


        };
        return allwords;


    }
}
