package com.secretbiology.taboo.words;

//This set was modified from following websites :
// (1) https://embracingchina.files.wordpress.com/2014/08/taboo-game.pdf on 28th May 2016
// (2) https://en.islcollective.com

public class WordSet1 {

    public String[][] words() {
        String[][] allwords = {

                {" Boing ", " Noise ", " Bouncy ", " Ball ", " Trampoline ", " Bam "},
                {" Float ", " Swim ", " Surface ", " Parade ", " Balloon ", " Root Beer "},
                {" Beach ", " Ball ", " Sand ", " Ocean ", " Bum ", " Sun "},
                {" Exactly ", " Precise ", " Amount ", " Understand ", " True ", " Time "},
                {" Will ", " Free ", " Volition ", " Own ", " Decision ", " Testament "},
                {" Horn ", " Car ", " Beep ", " Honk ", " Steering Wheel ", " Hit "},
                {" Booze ", " Alcohol ", " Beer ", " Spirits ", " Wino ", " Drunk "},
                {" Nightmarish ", " Dream ", " Bad ", " Monsters ", " Sleep ", " Scary "},
                {" Canberra ", " Australia ", " Capital ", " City ", " Australian Capital Territory ", " Act "},
                {" Huge ", " Big ", " Vast ", " Jumbo ", " Enormous ", " Gigantic "},
                {" Budget ", " Finance ", " Plan ", " Rental ", " Annual ", " Monthly "},
                {" Ladle ", " Soup ", " Cook ", " Kitchen ", " Spoon ", " Pot "},
                {" Colour ", " Light ", " See ", " Prism ", " Crayons ", " Colourful "},
                {" Energy ", " Light ", " Sound ", " Power ", " Sun ", " Work "},
                {" Bladder ", " Pee ", " Empty ", " Drink ", " Water ", " Infection "},
                {" Purse ", " Lipstick ", " Wallet ", " Keys ", " Change ", " Gum "},
                {" Lovers ", " Rectangles ", " Relations ", " Forever ", " Two ", " Couple "},
                {" Roti ", " Curry ", " Indian ", " Grains ", " Food ", " Cook "},
                {" Anaconda ", " Snake ", " Reptile ", " Non-Venomous ", " Crawl ", " Amazon "},
                {" Peach ", " Fruit ", " Beer ", " Georgia ", " Apple ", " Sweet "},
                {" Chat ", " Talk ", " Aim ", " Text ", " Messaging ", " Whatsapp "},
                {" Pixel ", " Camera ", " Photo ", " Image ", " Units ", " Figure "},
                {" Browser ", " Internet Explorer ", " Chrome ", " Firefox ", " Safari ", " Internet "},
                {" Toyota ", " Car ", " Japan ", " Automobil ", " Company ", " Ford "},
                {" Hermione ", " Harry Potter ", " Ron Weasley ", " Hogwarts ", " Dumbledore ", " Magic "},
                {" Poker ", " Chips ", " Gambling  ", " Casino ", " Cards ", " Royal Flush "},
                {" Genetics ", " Genes ", " DNA ", " Generation ", " Heredity ", " Mendel "},
                {" Online ", " Texting ", " Internet ", " Whatsapp ", " Chatting ", " Facebook "},
                {" Catwalk ", " Fashion Show ", " Model ", " Runway ", " Go around ", " Pose "},
                {" Emirates ", " UAE ", " Airline ", " International ", " Middle East ", " Flight "},
                {" Moss ", " Slime ", " Fungi ", " Plant ", " Green ", " Fluffy "},
                {" Arlington ", " Pentagon ", " Clarendon ", " Cemetary ", " Reagan Airport ", " Crystal City "},
                {" Penultimate ", " Second ", " Last ", " End ", " Before ", " Next "},
                {" Sweater ", " Soft ", " Clothing ", " Top ", " Warm ", " Cold "},
                {" Bra ", " Underwear ", " Lingerie ", " Women", " Girls ", " Private "},
                {" Messy ", " Not Tidy ", " Barcelona Fc ", " Football ", " Not Neat ", " Disorder "},
                {" ASAP ", " As ", " Soon ", " Possible ", " Message ", " Text "},
                {" Kodak ", " Film ", " Company ", " Pictures ", " Camera ", " Image "},
                {" Peanuts ", " Cashew ", " Butter ", " Boiled ", " Salted ", " Roasted "},
                {" Okapi ", " Zebra ", " Giraffe ", " Long Tongue ", " Stripes ", " Animal "},
                {" Event ", " Circumstance ", " Development ", " Episode ", " Happening ", " Occasion "},
                {" Shark ", " Big Teeth ", " See ", " Fish ", " Ocean ", " Dangerous "},
                {" Bushbaby ", " Big Eyes ", " Noisy ", " Night ", " Galago  ", " Wild "},
                {" Helix ", " Spiral ", " Ladders ", " DNA ", " Snail-Shell ", " Screw-Thread "},
                {" Caramel ", " Sweet ", " Sugar ", " Chocolate ", " Caramelised ", " Ice-cream "},
                {" Strapless ", " Dress ", " Bra ", " Shoulders ", " Lingerie ", " Women "},
                {" Wombat ", " Slow ", " Brown ", " Fat ", " Short ", " Hairy "},
                {" Wok ", " Chilli ", " Hot ", " Tasty ", " Crispy ", " Food "},
                {" Japan ", " Tokyo ", " Asian ", " Sushi ", " Hiroshima ", " Country "},
                {" Narwhals ", " Unicorn ", " Underwater ", " Fish ", " Swim ", " Commotion "},
                {" Photographer ", " Lens ", " Pictures ", " Weddings ", " Studio ", " Camera "},
                {" Leggings ", " Tight ", " Black ", " Wear ", " Stretchy ", " Women "},
                {" Grasshopper ", " Insect ", " Green ", " Drink ", " Buggy Eyed ", " Jump "},
                {" Manufacture ", " Make ", " Assemble ", " Build ", " Construct ", " Produce "},
                {" Biscuit ", " Crunch ", " Sweet ", " Tea ", " Snack ", " Crumbly "},
                {" Jupiter ", " Solar System ", " Europa ", " Planet ", " Sun ", " Callisto "},
                {" Taboo ", " Game ", " Guess ", " Words ", " Playing ", " Moment "},
                {" Nepal ", " South Asia ", " Himalayas ", " Buddha ", " Mount Everest ", " Country "},
                {" Justify ", " Excuse ", " Rationalize ", " Explain ", " Vindicate ", " Account For "},
                {" Ladies ", " Chicks ", " Girls ", " Female ", " Lady ", " She "},
                {" Bikini ", " Beach ", " Women ", " Undergarments ", " Wear ", " Bra "},
                {" Students ", " School ", " Homework ", " Teacher ", " Friends ", " University "},
                {" Aquarium ", " Water ", " Tank ", " Glass ", " Fish ", " Aquatic "},
                {" Magma ", " Lava ", " Inside ", " Rock ", " Melting ", " Heat "},
                {" Cow ", " Mad ", " Disease ", " Steak ", " Moo ", " Dance "},
                {" Chitterlings ", " Pig ", " Intestine ", " Smelly ", " Bowel ", " Food "},
                {" Author ", " Book ", " Write ", " Name ", " Pen ", " Who "},
                {" Migration ", " Move ", " Place ", " Group ", " New Place ", " Geese "},
                {" Grandpa ", " Father ", " House ", " Relatives ", " Grandfather ", " Old "},
                {" Vernacular ", " Slang ", " Language ", " Region ", " Dialect ", " Colloquial "},
                {" Aorta ", " Artery ", " Vein ", " Blood ", " Heart ", " Chest "},
                {" Soliloquy ", " This ", " Is ", " A ", " English ", " Term "},
                {" Blood ", " Gore ", " Red ", " Ooze ", " Heart ", " Vein "},
                {" Sangria ", " Wine ", " Drink ", " Spain ", " Fruit ", " Jug "},
                {" Mcdonald ", " Food ", " Restaurant ", " Waiter ", " Burger ", " Fish "},
                {" Diabetes ", " Sugar ", " Insulin ", " Medical ", " Sweet ", " Disease "},
                {" Note ", " Write ", " Post ", " Stick ", " Remember ", " Musical "},
                {" Antiquity ", " Old ", " Expensive ", " Furniture ", " Rare ", " Antique "},
                {" Element ", " Wind ", " Storm ", " Snowstorm ", " Periodic Table ", " Volcano Run "},
                {" Currency ", " Dollars ", " Money ", " Cash ", " Bank ", " Converter "},
                {" Anthus ", " Pipits ", " Genus ", " Meadow ", " Ant ", " Thus "},
                {" Kindle ", " Amazon ", " Reader ", " Book ", " E-Ink ", " Burn "},
                {" Spencer ", " Dog ", " Bark ", " Walked ", " Animal ", " Pet "},
                {" Parker ", " Pen ", " Brand ", " Ink ", " Write ", " Expensive "},
                {" Far ", " Long ", " Way ", " Off ", " Distant ", " Away "},
                {" Limo ", " Dance ", " Date ", " Night ", " Dress ", " Prom "},
                {" Sweets ", " Sugar ", " Mouth ", " Chewy ", " Packet ", " Hard "},
                {" Fabric ", " Cloth ", " Rug ", " Cotton ", " Nylon ", " Rayon "},
                {" Stamina ", " Strength ", " Juice ", " Oxygen ", " Tired ", " Weak "},
                {" Soap ", " Clean ", " Dove ", " Zest ", " Shower ", " Dirt "},
                {" Door ", " Open ", " Close ", " Lock ", " Revolving ", " Garage "},
                {" Cousin ", " Family ", " Aunt ", " Uncle ", " Mother ", " Father "},
                {" Care ", " Custody ", " Keep ", " Supervision ", " Guardian ", " Charge "},
                {" Venice ", " Italy ", " Gondolas ", " Canals ", " Water ", " City "},
                {" Jesus ", " Christ ", " Christmas ", " Baby ", " Disciples ", " Mary "},
                {" Stereo ", " Music ", " Lyrics ", " Artist ", " Band ", " Singer "},
                {" Impute ", " Credit ", " Attribute ", " Charge ", " Lay ", " Assign "},
                {" Mint ", " Green ", " Vegetable ", " Gum ", " Home ", " Food "},
                {" Direct ", " Straight ", " Non Stop ", " Through ", " Undeviating ", " Straight Forward "},
                {" Pets ", " Dog ", " Bird ", " Animal ", " Creature ", " Duck "},
                {" Affection ", " Love ", " Feelings ", " Care ", " Kind ", " Marriage "},
                {" Honk ", " Car ", " Horn ", " Noise ", " Goose ", " Beep "},
                {" Neptune ", " King ", " Under The Sea ", " Fork Spear ", " Crown ", " Mermaid "},
                {" Blank ", " Empty ", " Bare ", " Clear ", " Vacant ", " Void "},
                {" Stocking ", " Sock ", " Stuffers ", " Christmas ", " Hangs ", " Candy "},
                {" Tub ", " Water ", " Bathroom ", " Soap ", " Clean ", " Bubbles "},
                {" Jump ", " Kangaroo ", " Hop ", " High ", " Tall ", " Low "},
                {" Boardwalk ", " Beach ", " Atlantic City ", " Funnel Cake ", " Sand ", " Rides "},
                {" Education ", " Degree ", " School ", " Diploma ", " Learn ", " Classroom "},
                {" Designer ", " Draw ", " Interior ", " Architect ", " Computer ", " Create "},
                {" Surf ", " Excel ", " Detergent ", " Browse ", " Clean ", " Wash "},
                {" Grenade ", " Bomb ", " Explosive ", " Army ", " Throw ", " Blow "},
                {" Skunk ", " Smelly ", " Black ", " Animal ", " Striped ", " Spray "},
                {" Mario ", " Video Game ", " Red ", " Plumber ", " Jump ", " Italian "},
                {" Computer ", " Data ", " File ", " Monitor ", " Keyboard ", " Mouse "},
                {" Stench ", " Fart ", " Smell ", " Gross ", " Air ", " Stink "},
                {" Request ", " Please ", " Thank You ", " Work ", " Accepted ", " Rejected "},
                {" Artist ", " Paint ", " Sketch ", " Brush ", " Frame ", " Picasso "},
                {" Masticate ", " Eat ", " Chew ", " Consume ", " Devour ", " Teeth "},
                {" Positivism ", " Auguste Comte ", " Scientific ", " Empirical ", " Knowledge ", " Objective "},
                {" Power ", " Speed ", " Strength ", " Electricity ", " Fuel ", " Coal "},
                {" Unicorn ", " Horn ", " Horse ", " Fantasy ", " Mythical ", " White "},
                {" Staff ", " Bark ", " Cute ", " Breed ", " Bull ", " Four Legs "},
                {" Admire ", " Consider ", " Esteem ", " Honor ", " Respect ", " Value "},
                {" Fizz ", " Bubble ", " Cream ", " Froth ", " Sizzle ", " Lather "},
                {" Height ", " Peak ", " Summit ", " Top ", " Altitude ", " Tall "},
                {" Mount ", " Grow ", " Enlarge ", " Rise ", " Multiply ", " Build "},
                {" Bakery ", " Cakes ", " Pastries ", " Buy ", " Sell ", " Chef "},
                {" Tickle ", " Laughter ", " Under Arm ", " Itchy ", " Laugh ", " Wiggle "},
                {" Shoulder ", " Body ", " Part ", " Head ", " Arms ", " Carry "},
                {" Nosebleed ", " Red ", " Punch ", " Face ", " Nostril ", " Blood "},
                {" Desire ", " Light ", " Obedience ", " Valor ", " Energy ", " Honor "},
                {" Interval ", " Time ", " Period ", " Level ", " Speed ", " Measurement "},
                {" Hippy ", " Peace ", " Love ", " Tie Die ", " Happiness ", " Change World "},
                {" Plato ", " Philosopher ", " Greek ", " Aristotle ", " Cave ", " Socrates "},
                {" Create ", " Produce ", " Write ", " Make ", " Start ", " Spawn "},
                {" Houseplant ", " Flower ", " Inside ", " Water ", " Pot ", " Planter "},
                {" Bachelor ", " Single ", " Married ", " Show ", " Party ", " Man "},
                {" Cowboy ", " Boots ", " Horse ", " Spurs ", " Dallas ", " Texas "},
                {" Acropolis ", " Fortified ", " Elevated Ground ", " Greece ", " Hub ", " Polis "},
                {" Dig ", " This ", " A Hole ", " Further ", " Deeper ", " Oil "},
                {" Printer ", " Machine ", " Prints ", " Books ", " Computer ", " Paper "},
                {" Earrings ", " Jewellery ", " Women S Wear ", " Diamonds ", " Pair ", " Shiny "},
                {" Solved ", " Papers ", " Answers ", " Maths ", " English ", " Science "},
                {" Slit ", " Cut ", " Opening ", " Throat ", " Skirt ", " Wrist "},
                {" Chevy ", " Chevrolet ", " Vehicle ", " Cars ", " Jeep ", " Cross "},
                {" Upgrade ", " Promote ", " Advance ", " Jump ", " Elevate ", " Raise "},
                {" Farmer ", " Milk ", " Cow ", " Animals ", " Barn ", " Food "},
                {" Abominable ", " Hateful ", " Disgusting ", " Detestable ", " Despicable ", " Loathsome "},
                {" Pacifier ", " Crying ", " Baby ", " Heart ", " Kids ", " Infant "},
                {" Consign ", " Address ", " Dispatch ", " Forward ", " Route ", " Ship "},
                {" Forge ", " Make ", " Build ", " Produce ", " Frame ", " Construct "},
                {" Monday ", " Week ", " Sunday ", " Tuesday ", " Thursday ", " Wednesday "},
                {" Gang ", " Gun ", " Drugs ", " Police ", " Jail ", " Violence "},
                {" Transcript ", " Grades ", " Marks ", " School ", " College ", " Job "},
                {" Mobiles ", " Messaging ", " Camera ", " Calling ", " Music ", " Video "},
                {" Lamp ", " Light ", " On ", " Off ", " Bright ", " Standing "},
                {" Skipper ", " Ship ", " Madagascar ", " Penguin ", " Captain ", " Sea "},
                {" Patch ", " Award ", " Scout ", " Fix ", " Together ", " Bind "},
                {" Games ", " Time Waster ", " Fun ", " Shoot ", " Score ", " Win "},
                {" Choke ", " Breathe ", " Inhale ", " Smoke ", " Cigarette ", " Food "},
                {" Pastry ", " Breakfast ", " Dessert ", " Crumble ", " Bakery ", " Sweet "},
                {" Classroom ", " Teacher ", " Student ", " School ", " Books ", " Board "},
                {" Feign ", " Fake ", " Pretend ", " Put On ", " Lie ", " Sham "},
                {" Agile ", " Sprint ", " Methodology ", " Business ", " Quick ", " Flexible "},
                {" Poverty ", " Hunger ", " Unfortunate ", " Homeless ", " Desperate ", " Suffering "},
                {" Intersect ", " Cut ", " Crosscut ", " Crossover ", " Crisscross ", " Across "},
                {" Alarm ", " Device ", " Warning ", " Security ", " Clock ", " Fear "},
                {" Chalk ", " Colors ", " Sidewalk ", " Pavement ", " Writing Utensil ", " Write "},
                {" Respect ", " Elder ", " Talent ", " Umpire ", " All ", " Parents "},
                {" Disc ", " Spangle ", " No Spangle ", " Round ", " Crooked ", " Right "},
                {" Comforting ", " Assisting ", " Remedy ", " Comfortable ", " Reassure ", " Uncomfortable "},
                {" Signature ", " Sign ", " Pen ", " Paper ", " Forum ", " Post "},
                {" Waitress ", " Serve ", " Tip ", " Menu ", " Food ", " Restaurant "},
                {" Flamingo ", " Pink ", " Bird ", " Animal ", " Zoo ", " Legs "},
                {" Jewellery ", " Neck ", " Ear ", " Diamond ", " Expensive ", " Wedding Ring "},
                {" Honking ", " Car ", " Horn ", " Beep ", " Duck ", " Noise "},
                {" Sunny ", " Outside ", " Yellow ", " Sun ", " Sky ", " Bright "},
                {" Help ", " Sos ", " Assist ", " Need ", " Accomplish ", " Call "},
                {" Puma ", " CD ", " Animal ", " Grass ", " Company ", " Sports "},
                {" Barbell ", " Dumbbells ", " Weights ", " Gym ", " Exercise ", " Train "},
                {" Rugby ", " Kick ", " Throw ", " Tackle ", " Run ", " Pass "},
                {" Kangaroo ", " Pouch ", " Hop ", " Animal ", " Australia ", " Captain "},
                {" Serenity ", " Calmness ", " Peace ", " Quietness ", " Tranquil ", " Stillness "},
                {" House ", " Doors ", " Windows ", " Roof ", " Floor ", " Gate "},
                {" Demon ", " Scary ", " Killers ", " Murders ", " Ghost ", " Spooky "},
                {" Cornucopia ", " Fruit ", " Thanksgiving ", " Centerpiece ", " Bountiful ", " Abundance "},
                {" Trinket ", " Knickknack ", " Whatnot ", " Toy ", " Gewgaw ", " Novelty "},
                {" Sheet ", " Paper ", " Sentence ", " Word ", " White ", " Ink "},
                {" Burgundy ", " Orange ", " Red ", " Maroon ", " Colour ", " Pink "},
                {" Souse ", " Douse ", " Duck ", " Dunk ", " Submerge ", " Submerse "},
                {" Cardinal ", " Bird ", " Red ", " Chirp ", " Spring ", " Bishop "},
                {" Myopia ", " Glasses ", " Eyes ", " Vision ", " Nearsightedness ", " Optometrist "},
                {" Nostril ", " Hair ", " Nose ", " Hole ", " Face ", " Pick "},
                {" Unicycle ", " Wheel ", " One ", " Round ", " Balance ", " Ride "},
                {" Michael ", " Jesus ", " Arch-Angel ", " Angel ", " Saint ", " God "},
                {" Ironic ", " Hipster ", " Meaning ", " Socratic ", " Opposite ", " Coincidence "},
                {" Mannequin ", " Doll ", " Puppet ", " Display ", " Wood ", " Cloth "},
                {" Media ", " TV ", " Movie ", " Music ", " Dance ", " News "},
                {" Fog ", " Clouds ", " Sight ", " Vision ", " War ", " Block "},
                {" Cheap ", " Brown ", " Asian ", " Money ", " Jew ", " Hamza "},
                {" Wax ", " Ear ", " Paper ", " Candle ", " Power ", " Hear "},
                {" Kitten ", " Purr ", " Meow ", " Pet ", " Dog ", " Cat "},
                {" Foundation ", " Charity ", " Organization ", " Groundwork ", " Basis ", " Institution "},
                {" Frustrated ", " Hyped ", " Out Of Pocket ", " Piss ", " Mad ", " Angry "},
                {" Spanish ", " Language ", " Hispanics ", " Speak ", " People ", " Spain "},
                {" Night ", " Day ", " Dark ", " Sleep ", " Shirt ", " Bed "},
                {" Midget ", " Alive ", " Person ", " Earth ", " Me Or U ", " Animate Thing "},
                {" Reunion ", " Highschool ", " Gathering ", " Friends ", " Enemies ", " Year "},
                {" Dress ", " Dresses ", " Coat ", " Pant ", " Beauty ", " Skirt "},
                {" Remote ", " Control ", " Game ", " Instruction ", " Distance ", " Move "},
                {" Telephone ", " Mobile ", " Talk ", " Ring ", " Bell ", " Communication "},
                {" Wreck ", " Ship ", " Sea ", " Go Down ", " Storm ", " Damage "},
                {" Poodle ", " Dog ", " French ", " Breed ", " Curls ", " Bow "},
                {" Talcum ", " Baby ", " Powder ", " White ", " Smell ", " Dry "},
                {" Thrice ", " Twice ", " Once ", " Times ", " Three ", " Triple "},
                {" Jaw ", " Strong ", " Joint ", " Shark ", " Chew ", " Teeth "},
                {" Fix ", " Repair ", " Accident ", " Handyman ", " Tools ", " Screwdrivers "},
                {" Atheist ", " God ", " Religion ", " Church ", " Rational ", " Creation "},
                {" Bunny ", " Hop ", " Jump ", " Pet ", " Animal ", " Fluffy "},
                {" Underwear ", " But ", " Body ", " Cloth ", " Swimsuit ", " Pants "},
                {" Waffles ", " Syrup ", " Maple ", " Sap ", " Butter ", " Pancake "},
                {" Advance ", " Boost ", " Jump ", " Raise ", " Rise ", " Increase "},
                {" Technology ", " Robots ", " New ", " Science ", " Helps ", " Humans "},
                {" Cambridge ", " University ", " England ", " Punt ", " Blue ", " City "},
                {" Hairspray ", " Movie ", " Beauty Product ", " Musical ", " Baltimore ", " Film "},
                {" Flounder ", " Ariel ", " Mermaid ", " Fish ", " Sea ", " Clown "},
                {" Lane ", " Shoulder ", " Cars ", " Pass ", " Drive ", " Turn "},
                {" Bankrupt ", " Break ", " Bust ", " Ruin ", " Impoverish ", " Clean "},
                {" Mirror ", " Glass ", " Daily ", " Make-up ", " Face ", " Reflection "},
                {" Royalty ", " King ", " Queen ", " Prince ", " Princess ", " Castle "},
                {" America ", " Freedom ", " Strong ", " Continent ", " United States ", " G. Bush "},
                {" Castles ", " Moat ", " Knight ", " Drawbridge ", " Dungeon ", " Wall "},
                {" Judge ", " Authority ", " Honor ", " Legal ", " Moderator ", " Justice "},
                {" Four ", " Five ", " Before ", " Number ", " After ", " Three "},
                {" Magnet ", " Bar ", " Solenoid ", " Attract ", " Metals ", " Loop "},
                {" Funeral ", " Bury ", " Die ", " Pass Away ", " Dead ", " Coffin "},
                {" Chirp ", " Birds ", " Cricket ", " Sound ", " Silent ", " Annoying "},
                {" Ant ", " Hill ", " Eater ", " Aunt ", " Bites ", " Farm "},
                {" Paint ", " Color ", " Brush ", " Wall ", " Bucket ", " Liquid "},
                {" Freak ", " Super ", " Weird ", " Wacky ", " Show ", " Friday "},
                {" Mascara ", " Eyes ", " Lashes ", " Tube ", " Comb ", " Adam Lambert "},
                {" Boil ", " Water ", " Pus ", " Bump ", " Bust ", " Inflammation "},
                {" Burden ", " Proof ", " Weight ", " Hinder ", " Leave ", " Down "},
                {" Search ", " Party ", " Engine ", " Find ", " Seek ", " Look "},
                {" Creative ", " Imaginative ", " Craft ", " Create ", " Unique ", " Artsy "},
                {" Snowmobile ", " Snow ", " Vehicle ", " Ski ", " Track ", " Cold "},
                {" Improvisation ", " Game ", " Comedy ", " Spontaneous ", " Suggestion ", " Unplanned "},
                {" Ornaments ", " Christmas ", " Decoration ", " Tree ", " Star ", " Lights "},
                {" Freud ", " Psychology ", " Libido ", " Ego ", " Subconscious ", " Book "},
                {" Cutie ", " Cute ", " Pet Name ", " Couple ", " Orange ", " Love "},
                {" Turquoise ", " Blue ", " Green ", " Water ", " Color ", " Kind Of "},
                {" Reevaluate ", " Rethink ", " Reconsider ", " Consider ", " Review ", " Survey "},
                {" Toddler ", " Child ", " Baby ", " Young ", " Cry ", " Kid "},
                {" Martian ", " Mars ", " Space ", " Favorite ", " Ufo ", " Alien "},
                {" Lottery ", " Lotto ", " Chance ", " Luck ", " Game ", " Fun "},
                {" Ferret ", " Long ", " Curious ", " Weasel ", " Mink ", " Furry "},
                {" Tibet ", " Himalaya ", " China ", " Asia ", " Tibetan ", " Buddhist "},
                {" Blitzkrieg ", " German ", " Poland ", " Fast ", " War ", " Tank "},
                {" School ", " Cabinets ", " Teachers ", " Students ", " Books ", " Homeworks "},
                {" Zen ", " Chinese ", " Relax ", " Calm ", " Garden ", " Serene "},
                {" Erase ", " Eraser ", " Non Dust ", " Natraj ", " Stationary ", " Education "},
                {" Metronome ", " Time ", " Click ", " Swing ", " Music ", " Beat "},
                {" Ray ", " Sun ", " Point ", " Direction ", " Light ", " Gun "},
                {" Vaccine ", " Needle ", " Shot ", " Doctor ", " Sick ", " Flu "},
                {" Tsunami ", " Earthquake ", " Sea ", " Disaster ", " Waves ", " Volcano "},
                {" Avid ", " School ", " Interest ", " College ", " Favorite ", " binder checks "},
                {" Twin ", " Alike ", " Similar ", " Sisters ", " Brothers ", " Look "},
                {" Saxophone ", " Concert ", " Instrument ", " Band ", " Music ", " Romantic "},
                {" Longhorn ", " Austin ", " University ", " Texas ", " Orange ", " Animal "},
                {" Antiseptic ", " Immaculate ", " Clean ", " Spotless ", " Stainless ", " Unsoiled "},
                {" Burma ", " Country ", " Asia ", " Military Junta ", " Dictator ", " Southeast "},
                {" Hippopotamus ", " Big ", " Attacks ", " Hippo ", " Zoo ", " Shoes "},
                {" Cigar ", " Tobacco ", " Cigarette ", " Smoke ", " Cuba ", " Stogie "},
                {" Who ", " That ", " Where ", " Why ", " How ", " What "},
                {" Cruise ", " Sea ", " Water ", " Waves ", " Food ", " Sun "},
                {" Ireland ", " Island ", " Emerald ", " Green ", " Country ", " Irish "},
                {" Essentials ", " Toothbrush ", " Shelter ", " Food ", " Money ", " Toothpaste "},
                {" Dog ", " Best ", " Friend ", " Animal ", " World ", " Bodyguard "},
                {" Stamp ", " Postage ", " Foot ", " Ink ", " Mail ", " Lick "},
                {" Sunglass ", " Glares ", " Shades ", " Protection ", " Eye ", " Accessory "},
                {" Dinosaur ", " Extinct ", " Ancient ", " Rex ", " Meteor ", " Jurassic "},
                {" Usher ", " Confessions ", " Church ", " Wedding ", " Chili ", " Raymond "},
                {" Boys ", " Big ", " Strong ", " Hight ", " Small ", " Funny "},
                {" Proton ", " Neutron ", " Particle ", " Electron ", " Nucleus ", " Positive "},
                {" Kiwi ", " Green ", " Fruit ", " Tasty ", " Nasty ", " Seed "},
                {" Panama ", " Country ", " Canal ", " Two Ocean ", " Dollar ", " Spanish "},
                {" Sandals ", " Slippers ", " Shoes ", " Feet ", " Sand ", " Wear "},
                {" Federalism ", " Laboratory ", " Government ", " States ", " Divided ", " National "},
                {" Mother ", " Mom ", " Mommy ", " Mummy ", " Mum ", " Caretaker "},
                {" Wasabi ", " Green ", " Spicy ", " Japanese ", " Sushi ", " Pain "},
                {" Swerve ", " Cut ", " Sheer ", " Skew ", " Veer ", " Chop "},
                {" Piglet ", " Pig ", " Winnie The Pooh ", " Hog ", " Tigger ", " Pink "},
                {" Slope ", " Curve ", " Hill ", " Mountain ", " Steep ", " Park "},
                {" Newspaper ", " Editor ", " Extra ", " Feature ", " Ink ", " Newsstand "},
                {" Vatican ", " Pope ", " Italy ", " Church ", " John Paul ", " Catholic "},
                {" Channel ", " English ", " Brand ", " Television ", " Lipstick ", " Expensive "},
                {" Curse ", " Witch ", " Mummy ", " Release ", " Bad Luck ", " Clarity "},
                {" Tools ", " Mechanic Use ", " Helps ", " Fix ", " Repair ", " Connect "},
                {" Bomb ", " Boom ", " Explode ", " Arab ", " Airport ", " Suicide Vest "},
                {" Cheery ", " Red ", " Pit ", " Fruit ", " Tree ", " Pie "},
                {" Asymptote ", " Function ", " Limit ", " Graph ", " Cartesian ", " Parabola "},
                {" Unclean ", " Soiled ", " Dirty ", " Filthy ", " Grubby ", " Smutty "},
                {" Flabbergasted ", " Mouse ", " Isolation ", " Depression ", " Piano ", " Czechoslovakia "},
                {" Ram ", " Random ", " Memory ", " Fast ", " Gigabytes ", " Computer "},
                {" Ford ", " Mustang ", " Explorer ", " Company ", " Car ", " Focus "},
                {" Saw ", " Horror Movie ", " Key ", " Blood ", " Horrible ", " Die "},
                {" Gentle ", " Hard ", " Soft ", " Careful ", " Break ", " Careless "},
                {" Garrulous ", " Talk ", " Person ", " Palaver ", " Very ", " Continuous "},
                {" Baboon ", " Red ", " Butt ", " Monkey ", " Silly ", " Animal "},
                {" Gallon ", " Milk ", " Measure ", " Liquid ", " Water ", " Jug "},
                {" Praise ", " Hail ", " Celebrate ", " Applause ", " Commend ", " Acclaim "},
                {" Fish ", " Salmon ", " Trout ", " Lobster ", " Tuna ", " Shrimp "},
                {" Personification ", " Person ", " Human ", " Alive ", " Thing ", " Animal "},
                {" Monster ", " Scarey ", " Energy Drink ", " Closet ", " Under Bed ", " Boo "},
                {" Dominate ", " Win ", " Destroy ", " Margin ", " Completely ", " Utterly "},
                {" Stomach ", " Food ", " Body Part ", " Digestion ", " Muscular Bag ", " Oesophagus "},
                {" Child ", " Kid ", " Small ", " Young ", " Adult ", " Children "},
                {" Pizza ", " Round ", " Delivery ", " Crust ", " Sauce ", " Cheese "},
                {" Granddaughter ", " Generation ", " Kids ", " Mom ", " Children ", " Parent "},
                {" Nose ", " Smell ", " Sense ", " Hairy ", " Oily ", " Boogers "},
                {" Coffee ", " Cream ", " Cup ", " Filter ", " Pot ", " Sugar "},
                {" Pavement ", " Road ", " Asphalt ", " Alternative Rock ", " Driveway ", " Tar "},
                {" Duke ", " Carolina ", " University ", " College ", " Study ", " Admission "},
                {" Stockings ", " Christmas ", " Socks ", " Lingerie ", " Legs ", " Fishnet "},
                {" Bollard ", " Barrier ", " Fence ", " Railing ", " Guard ", " Protection "},
                {" Pebble ", " Stone ", " Small ", " Gravel ", " Skim ", " Dog "},
                {" Sunrise ", " Sunshine ", " Sun ", " Lovely Feeling ", " Insane ", " Rise "},
                {" Drees ", " Wear ", " Skirt ", " Woman ", " Girl ", " Clothes "},
                {" Tobacco ", " Cancer ", " Slave ", " Cigarette ", " Smoke ", " Nicotine "},
                {" Missing ", " Gone ", " Dog ", " Lost ", " There ", " Forgotten "},
                {" Pink ", " Color ", " Girl ", " Female ", " Bear ", " Blue "},
                {" Phoenix ", " Bird ", " Fictional ", " Harry Potter ", " Flames ", " Rebirth "},
                {" Avalanche ", " Snow ", " Hill ", " Down ", " Sky ", " Mountain "},
                {" Allergy ", " Sneeze ", " Cough ", " Pollen ", " Spring ", " Medical Condition "},
                {" Peppermint ", " Patty ", " Cool ", " Candy ", " Ice Cream ", " Candy Cane "},
                {" Snack ", " Food ", " Hungry ", " Crackers ", " Sweets ", " Treat "},
                {" Regeneration ", " Doctor Who ", " Skin ", " Growth ", " New ", " More "},
                {" Surfy ", " Fat ", " Belly ", " Rashes ", " Cries ", " Candy "},
                {" That ", " Who ", " Where ", " Why ", " How ", " What "},
                {" Strategy ", " Genre ", " Game ", " Thinking ", " Real Time ", " Role Playing "},
                {" Dollar ", " Money ", " Currency ", " Cash ", " Bills ", " Washington "},
                {" Calendar ", " Month ", " Week ", " Day ", " Years ", " Numbers "},
                {" Numbers ", " One ", " Two ", " Tree ", " Four ", " Five "},
                {" Skin ", " Touch ", " Feel ", " Body ", " Bruises ", " Acne "},
                {" Summer ", " Hot ", " Beaches ", " Vacation ", " Hawaii ", " Surfing "},
                {" Assassin ", " Game ", " Creed ", " Kill ", " Ninja ", " Murder "},
                {" Colosseum ", " Gladiator ", " Rome ", " Monument ", " Amphitheatre ", " Bull/Lion "},
                {" Grape ", " Violet ", " Juicy ", " Fruit ", " Small Bones ", " Delicious "},
                {" Perfume ", " Bottle ", " Expensive ", " Smell ", " Flowers ", " Liquid "},
                {" Cumble ", " Soft ", " Blanket ", " Sleep ", " Nightime ", " Fuzzy "},
                {" Book ", " Pages ", " Information ", " Knowledge ", " Collection ", " Published "},
                {" Crutches ", " Legs ", " Feet ", " Injury ", " Bone ", " Walk "},
                {" Examination ", " Test ", " Knowledge ", " Study ", " Inspection ", " School "},
                {" Leave ", " Somewhere ", " Go ", " Car ", " Walk ", " House "},
                {" Waist ", " Middle ", " Belt ", " Bend ", " Expanding ", " Body "},
                {" Palestine ", " Jerusalem ", " Israel ", " Middle East ", " Jesus ", " Olive Oil "},
                {" Carbonated ", " Coke ", " Soda ", " Pop ", " Drink ", " Water "},
                {" Photo ", " Picture ", " Frame ", " Lens ", " Camera ", " Digital "},
                {" Serving ", " Helping ", " Portion ", " Piece ", " Mess ", " Serve "},
                {" Kilometer ", " Mile ", " Meter ", " Car ", " Pounds ", " Kilo "},
                {" Acne ", " Red ", " Zits ", " Teenagers ", " Dots ", " Pimples "},
                {" Ceiling ", " Roof ", " Floor ", " Ground ", " Height ", " Above "},
                {" Translate ", " International ", " From/To ", " Tell ", " Understand ", " Language "},
                {" Swim ", " Team ", " Stroke ", " Crawl ", " Butterfly ", " Pool "},
                {" Breast ", " Chicken ", " Woman ", " Bra ", " Chest ", " Milk "},
                {" Ottoman ", " Chair ", " Turkey ", " Seat ", " Sofa ", " Empire "},
                {" Haunted ", " Churchyard ", " Funeral ", " Ghost ", " Witches ", " Graveyard "},
                {" Waiter ", " Restaurant ", " Receipt ", " Food ", " Service ", " Tip "},
                {" Stare ", " Eye ", " Look ", " Contest ", " Blink ", " Goat "},
                {" Emotion ", " Happy ", " Sad ", " Angry ", " Excited ", " Cry "},
                {" Manage ", " Manager ", " Office ", " Factory ", " Industry ", " Money "},
                {" Gore ", " Graphic ", " Violence ", " Violent ", " Extreme ", " Hurtful "},
                {" Nasty ", " Hurtful ", " Spiteful ", " Mean ", " Abuse ", " Verbal "},
                {" Division ", " Agency ", " Arm ", " Branch ", " Organ ", " Department "},
                {" Talking ", " Communicate ", " Speak ", " Mouth ", " Conversation ", " Tell "},
                {" Tokyo ", " China ", " Steakhouse ", " Chinese ", " Korean ", " City "},
                {" Lobotomy ", " Frontal Lobe ", " Psychology ", " Operation ", " Insane ", " Mental Institution "},
                {" Kitchen ", " Cooking ", " Chef ", " Food ", " Eating ", " Baking "},
                {" Face ", " Sad ", " Happy ", " Depressed ", " Fainting ", " Shocked "},
                {" Himalayas ", " Mount ", " Everest ", " Hight ", " Climb ", " Peak "},
                {" Bearing ", " Air ", " Manner ", " Style ", " Address ", " Ball "},
                {" Alliteration ", " Repetition ", " Sound ", " Sentence ", " Same ", " Beginning "},
                {" Shield ", " Armour ", " Protect ", " Medieval ", " Knight ", " Metal "},
                {" Silk ", " Moth ", " Soft ", " Sheets ", " Robe ", " Fabric "},
                {" Ridiculous ", " Silly ", " Crazy ", " Nuts ", " Whacky ", " Funny "},
                {" Stratosphere ", " Air ", " Earth ", " Layer ", " Atmosphere ", " Space "},
                {" Solid ", " Gas ", " Liquid ", " Hard ", " Soft ", " Mathematics "},
                {" Carnival ", " People ", " Street ", " Drinks ", " Music ", " Dance "},
                {" Color ", " Rainbow ", " Crayon ", " Red ", " Blue ", " Green "},
                {" Stage ", " Perform ", " Sing ", " Dance ", " Broadway ", " Act "},
                {" Exam ", " Prepare ", " Paper ", " Check ", " Retest ", " Test "},
                {" Coaching ", " Swimming ", " School ", " Help ", " Classes ", " Fee "},
                {" Roaches ", " Nasty ", " Crawl ", " Floor ", " South ", " Small "},
                {" Monomial ", " One ", " Number ", " Letter ", " Trinomial ", " Binomial "},
                {" Pause ", " Play ", " Stop ", " Rewind ", " Fast Forward ", " Hesitate "},
                {" Photograph ", " Picture ", " Camera ", " Take ", " Moment ", " Upload "},
                {" Girlfriend ", " Boyfriend ", " Go Out With ", " Date ", " Wife ", " Girl "},
                {" Polyphemus ", " Cyclops ", " Odysseus ", " Nobody ", " Sheep ", " Eye "},
                {" Oatmeal ", " Breakfast ", " Cereal ", " Quaker ", " Horse ", " Fiber "},
                {" Crescendo ", " Music ", " Volume ", " Loud ", " Increase ", " Conduct "},
                {" Promise ", " Keep ", " Break ", " Vow ", " Pinky ", " Oath "},
                {" Bank ", " Institution ", " Savings ", " Financial ", " Money ", " Deposit "},
                {" Camel ", " Hump ", " Water ", " Desert ", " Sahara ", " Dry "},
                {" Tradition ", " Culture ", " Country ", " Styles ", " Types ", " Everything "},
                {" Rectify ", " Fix ", " Problem ", " Solve ", " Correct ", " Sort "},
                {" Envelope ", " Container ", " Mail ", " Advertisements ", " Stamp ", " Paper "},
                {" Pimple ", " Pop ", " Pore ", " Pus ", " Acne ", " Teenagers "},
                {" Asylum ", " Crazy ", " Hospital ", " Mind ", " Doctor ", " Patient "},
                {" Hypothermia ", " Cold ", " Shivers ", " Frozen ", " Tissue ", " Temperature "},
                {" Travel ", " Plane ", " Transportation ", " Vacation ", " Family ", " Reunion "},
                {" Maimed ", " Disable ", " Disfigure ", " Limb ", " Defective ", " Impair "},
                {" Scanner ", " Computer ", " Device ", " Scan Images ", " Radar Searching ", " Scan Text "},
                {" Igloo ", " Ice ", " In Greenland ", " House ", " Eskimo ", " Frigid "},
                {" Fountain ", " Water ", " Musical ", " Lights ", " Shower ", " In Shapes "},
                {" Island ", " Beach ", " Sand ", " Lost ", " Land ", " Hawaii "},
                {" Host ", " Domain ", " Space ", " Bandwidth ", " Internet ", " Place "},
                {" Equator ", " Latitude ", " Pole ", " Degree ", " Warm ", " Center "},
                {" Howl ", " Bark ", " Wolf ", " Dog ", " Yowl ", " Whine "},
                {" Stairs ", " Steps ", " Walk ", " Climb ", " Feet ", " Incline "},
                {" Insusceptible ", " Immune ", " Impervious ", " Proof ", " Resistant ", " Withstand "},
                {" Stapler ", " Clip ", " Paper ", " Together ", " Bind ", " Refill "},
                {" Clothing ", " Shirt ", " Shorts ", " Pants ", " Socks ", " Scarf "},
                {" Park ", " Picnic ", " Kids ", " Walk ", " Ducks ", " Playground "},
                {" Illuminati ", " Devil ", " Secret Society ", " Evil ", " New World Order ", " Triangle & Eye "},
                {" Studs ", " Cones ", " Pointed ", " Modern ", " Punk ", " Sliver "},
                {" Ocean ", " Water ", " Indian ", " Salt ", " Sea ", " Pacific "},
                {" George ", " Jamaica ", " Ganja ", " Ganger ", " Curly ", " Soft "},
                {" Purge ", " Eradicate ", " Liquidate ", " Remove ", " Eliminate ", " Wipe "},
                {" Bulgaria ", " Country ", " Europe ", " Rose ", " Small ", " Not Very Popular "},
                {" Juggle ", " Clown ", " Balls ", " Throw ", " Toss ", " Hands "},
                {" Cuticle ", " Manicure ", " Pedicure ", " Skin ", " Dead ", " Nail "},
                {" Court ", " High ", " Supreme ", " Shuttle ", " Basketball ", " Tennis "},
                {" Sausage ", " Pork ", " Herb ", " Pig ", " Salami ", " Cumberland "},
                {" Open ", " Closed ", " Book ", " Shop ", " Free ", " Welcome "},
                {" Ponder ", " Consider ", " Contemplate ", " Mull ", " Think ", " Weigh "},
                {" Suds ", " Soap ", " Foam ", " Wash ", " Bath ", " Bubbles "},
                {" Roof ", " House ", " Top ", " Red ", " Tiles ", " Chimney "},
                {" Speakers ", " Music ", " Sound ", " Bass ", " Treble ", " Mid "},
                {" Chili ", " Pepper ", " South America ", " Plant ", " Spicy ", " Hot "},
                {" Lights ", " Christmas ", " Bulb ", " Flicker ", " Switch ", " Bright "},
                {" Punch ", " Fist ", " Fight ", " Fruit ", " Bowl ", " Boxing "},
                {" Indemnity ", " Security ", " Protection ", " Safe ", " Fraud ", " Insurance "},
                {" Beanstalk ", " Jack ", " Giant ", " Story ", " Plant ", " Green "},
                {" Vowels ", " Alphabet ", " Consonants ", " School ", " Learn ", " Wheel Of Fortune "},
                {" Honky ", " Cracker ", " Lazy ", " Unathletic ", " Redneck ", " Hater "},
                {" Egregious ", " Bad ", " Mistake ", " Error ", " Outstanding ", " Horrible "},
                {" Rhythm ", " Song ", " Sound ", " Poem ", " Beat ", " Dance "},
                {" Sibling ", " Sister ", " Brother ", " Child ", " Parents ", " Twins "},
                {" Vendetta ", " Revenge ", " Sicily ", " Feud ", " Italian ", " Punishment "},
                {" Dwelling ", " Home ", " Habitation ", " Lodging ", " Place ", " Residence "},
                {" Portrait ", " Family ", " Picture ", " Frame ", " Pose ", " Photo "},
                {" Pulverize ", " Ground ", " Powder ", " Mill ", " Bray ", " Crush "},
                {" Say ", " Communicate ", " Voice ", " Vent ", " Utter ", " Declare "},
                {" Gutter ", " Rain ", " Street ", " Leaves ", " Water ", " Clean "},
                {" Question ", " Ask ", " Answer ", " Interrogate ", " Period ", " Mark "},
                {" Rocks ", " Stones ", " Boulders ", " Minerals ", " Ground ", " Plymouth "},
                {" Payment ", " Cash ", " Cheque ", " Bank ", " Debtor ", " Creditor "},
                {" Circle ", " Shape ", " Hollow ", " Ring ", " Curved ", " Cycle "},
                {" Mitochondria ", " Cell ", " Power House ", " Cellular ", " Part ", " Human Cells "},
                {" Dislocate ", " Joint ", " Shoulder ", " Crystal Lattice ", " Injury ", " Pain "},
                {" Masterpiece ", " Theatre ", " Art ", " Work ", " Accomplishment ", " Classic "},
                {" Tendon ", " Band ", " Cord ", " Ligament ", " Tissue ", " Elastic "},
                {" Chipmunk ", " Alvin ", " Squirrel ", " Singing ", " Cartoon ", " Theodore "},
                {" Armadillo ", " Ball ", " Shell ", " Armoured ", " Animal ", " Small "},
                {" Appendix ", " Back ", " Book ", " Added ", " Organ ", " Removed "},
                {" Kindergarten ", " School ", " Preschool ", " Child ", " Teacher ", " Infant "},
                {" Horseradish ", " Pungent ", " Spice ", " Mustard ", " Wasabi ", " Horse "},
                {" Boyfriend ", " Male ", " Cute ", " Valentine ", " Date ", " Kiss "},
                {" Charades ", " Party ", " Games ", " Round ", " Team ", " Minute "},
                {" Battleship ", " Guns ", " Boat ", " Water ", " Float ", " Sailors "},
                {" Prosperity ", " Money ", " God ", " Healthy ", " Peace ", " No Lack "},
                {" Impala ", " Chevrolet ", " Gazelle ", " Antlers ", " Africa ", " Antelope "},
                {" River ", " Water ", " Lake ", " Stream ", " Mississippi ", " Runs "},
                {" Fertile ", " Soft Ground ", " Rich ", " Fruitful ", " Productive ", " Prolific "},
                {" Shell ", " Crab ", " Hard ", " Post Traumatic Stress ", " Egg ", " Calcium Carbonate "},
                {" Children ", " Dad ", " Mom ", " Sister ", " Brother ", " Grandmother "},
                {" Witch ", " Hocus Pocus ", " Sabrina ", " Warts ", " Broomstick ", " Cauldron "},
                {" Carpet ", " Indoor ", " Floor ", " Covering ", " Pile ", " Shag "},
                {" Odd ", " Weird ", " Opposite ", " Different ", " Quirky ", " Nerd "},
                {" Olaf ", " Snowman ", " Frozen ", " Disney ", " Josh Gad ", " Melt "},
                {" Signal ", " Road ", " Traffic ", " Lights ", " Cars ", " Ways "},
                {" Pearl ", " White ", " Shiny ", " Jewellery ", " Knit ", " Oyster "},
                {" Board ", " Key ", " Snow ", " Game ", " Of Education ", " Ship "},
                {" Gorgeous ", " Paris ", " Girls ", " Flowers ", " Beautiful ", " Pretty "},
                {" Nine ", " Ten ", " Eight ", " Number ", " Old ", " Count "},
                {" Pancake ", " Food ", " Butter ", " Syrup ", " Cooked ", " Eat Them "},
                {" Silver ", " Ware ", " Ring ", " Bullet ", " Spoon ", " Dollar "},
                {" Catholicism ", " Priest ", " Nuns ", " Vatican ", " Pope ", " Church "},
                {" Vienna ", " Austria ", " City ", " Capital ", " German ", " Belvedere "},
                {" Lunatic ", " Crazy ", " Psycho ", " Help ", " Psychiatrist ", " Toons "},
                {" Peculiar ", " Strange ", " Odd ", " Weird ", " Special ", " Unique "},
                {" Balloon ", " Party ", " Blow ", " Helium ", " Bouncy ", " Pop "},
                {" How ", " What ", " Why ", " Where ", " Who ", " That "},
                {" Purpose ", " Target ", " Job ", " Role ", " Task ", " Function "},
                {" Landing ", " Airplane ", " Base ", " Helicopter ", " Takeoff ", " Descent "},
                {" Hulk ", " Green ", " Dr. Banner ", " Angry ", " Gamma Ray ", " Purple "},
                {" Crime ", " Death ", " Injury ", " Loss ", " Burglary ", " Robbery "},
                {" Nemo ", " Clown ", " Fish ", " Dorey ", " Finding ", " Ocean "},
                {" Fired ", " Boss ", " Gun ", " Cannon ", " Shot ", " Job "}

        };
        return allwords;


    }
}
