package com.secretbiology.taboo.words;

//This set was modified from website : https://embracingchina.files.wordpress.com/2014/08/taboo-game.pdf on 28th May 2016

public class WordSet1 {

    public String[][] words(){
        String[][] allwords = {
                {"Blanket", "Warm", "Bed", "Pillow", "Soft", "Cold"},
                {"Shanghai", "Modern", "Big", "China", "Expo", "Famous"},
                {"Soccer", "Ball", "World Cup", "Black", "Sport", "Team"},
                {"Cheese", "Yellow", "White", "Pizza", "Food", "Italy"},
                {"Snail", "Round", "Slow", "River", "Eat", "Animal"},
                {"Husband", "Wife", "Ring", "Marry", "Man", "Friend"},
                {"Michael Jackson", "Dance", "Thriller", "Strange", "Famous", "Singer"},
                {"Underwear", "Small", "Clothing", "Every day", "Secret", "Under"},
                {"Girlfriend", "Boyfriend", "Beautiful", "Flowers", "Date", "female"},
                {"Giraffe", "Tall", "Africa", "Neck", "Long", "Yellow"},
                {"Wok", "Cook", "China", "Iron", "Dishes", "Pot"},
                {"Camera", "Photos", "Pictures", "Snapshot", "Travel", "Memories"},
                {"Slippers", "Warm", "Feet", "Winter", "House", "Soft"},
                {"Comb", "Brush", "Hair", "Smooth", "Small", "Beautiful"},
                {"Hamburger", "America", "Beef", "Bread", "McDonalds", "Unhealthy"},
                {"Polar Bear", "Cold", "Winter", "Alaska", "White", "Snow"},
                {"Penguin", "Bird", "Fly", "Animal", "Black", "White"},
                {"Glasses", "Eyes", "See", "Contacts", "Wear", "Face"},
                {"Popcorn", "Kernel", "Butter", "Sweet", "Microwave", "Snack Food"},
                {"Speech", "Give", "Speak", "Important", "Audience", "Nervous"},
                {"Furious", "Angry", "Red Face", "Hurt", "Rage", "Violent"},
                {"Jealousy", "Envy", "Emotion", "Compare", "Green", "Achieve"},
                {"Chicken Leg", "Bird", "Body", "Eat", "Food", "KFC"},
                {"Toilet", "Washroom", "WC", "Pee", "Poop", "Bathroom"},
                {"Wish", "Want", "Desire", "Hope", "Dream", "Long For"},
                {"Bench", "Sit", "Wooden", "Chair", "Long", "Park"},
                {"Exercise", "Run", "Sports", "Healthy", "Daily", "Morning"},
                {"Crown", "Head", "Gold", "King", "Queen", "Jewels"},
                {"Princess", "Prince", "Queen", "Daughter", "Royal", "Castle"},
                {"Internet", "Computer", "Web", "Surf", "Net", "Technology"},
                {"Jacket", "Coat", "Warm", "Clothes", "Sleeves", "Zipper"},
                {"Shower", "Rain", "Clean", "Water", "Every Day", "Bath"},
                {"Wind", "Blow", "Autumn", "Invisible", "Trees", "Kite"},
                {"Ice Cream", "Cold", "Summer", "Sweet", "Snack", "Cone"},
                {"Foreigner", "Teacher", "Different", "Outside", "Country", "Travel"},
                {"Church", "Sing", "Building", "Cross", "God", "Speaker"},
                {"Police", "Uniform", "Safety", "Peace", "Protect", "Siren"},
                {"Boots", "Winter", "Shoes", "Warm", "Fashion", "Snow"},
                {"Plane Ticket", "Expensive", "Flight", "Travel", "Paper", "Seat"},
                {"Turkey", "Bird", "Holiday", "Thanksgiving", "Big", "Tired"},
                {"Freezer", "Cold", "Refrigerator", "Ice", "Food", "Kitchen"},
                {"Soy Sauce", "Chinese", "Liquid", "Brown", "Cooking", "Salty"},
                {"Yoga Teacher", "Exercise", "Instructor", "Master", "Chinese", "Help"},
                {"Straw", "Hollow", "Horses", "Farm", "Drink", "Suck"},
                {"Leaf", "Tree", "Green", "Fall", "Plant", "Page"},
                {"Noun", "Verb", "Speech", "Adjective", "Person", "Place"},
                {"Carry", "Hold", "Pick up", "Move", "Transport", "Support"},
                {"Taxi", "Car", "Public", "Transport", "Fare", "City"},
                {"Blossom", "Flower", "Young", "Bud", "Spring", "Bloom"},
                {"Broom", "Sweep", "Floor", "Witch", "Wooden", "Dust"},
                {"Witch", "Broom", "Green", "Magic", "Halloween", "Powers"},
                {"Fork", "Spoon", "Knife", "Eat", "Prongs", "Divide"},
                {"Parade", "Line", "Crowd", "Floats", "Gather", "Holiday"},
                {"Fashion", "Clothes", "Model", "Girls", "Look", "Magazine"},
                {"Weeding Dress", "White", "Married", "Clothes", "Special", "Girls"},
                {"Kung Fu Panda", "Movie", "China", "Noodles", "Children", "Famous"},
                {"Marker", "Write", "Draw", "Colors", "Children", "Art"},
                {"Trash Can", "Rubbish", "Barrel", "Worthless", "Ruin", "Old"},
                {"Snowman", "Three", "Children", "Make", "Winter", "Outside"},
                {"Wings", "Bird", "Chicken", "Fly", "Arms", "Feathers"},
                {"Pilot", "Fly", "Plane", "Helicopter", "Man", "Travel"},
                {"Lawyer", "Argue", "Defend", "Law", "Client", "Crime"},
                {"Hair Salon", "Style", "Dye", "Wash", "Cut", "Barber"},
                {"Picture Frame", "Photo", "Memory", "Wood", "Glass", "Home"},
                {"Purse", "Leather", "Bag", "Money", "Women", "Carry"},
                {"Alligator", "Crocodile", "Green", "Animal", "Teeth", "Florida"},
                {"Orange", "Color", "Fruit", "Juicy", "Citrus", "Red"},
                {"Makeup", "Face", "Mascara", "Lipstick", "Girls", "Beautiful"},
                {"Tutor", "One on One", "Learn", "Make up", "Review"},
                {"Worry","Nervous", "Anxiety", "Stress", "Scared", "Trouble"},
                {"Moose", "Animal", "Mammal", "Forest", "Antlers", "Hunting"},
                {"Shampoo", "Conditioner", "Lather", "Wash", "Hair", "Shower"},
                {"Bridge", "Cross", "River", "Build", "Over", "Connect"},
                {"Nervous", "Anxious", "Test", "Difficulty", "Pressure", "Scared"},
                {"Camel", "Hump", "Desert", "Animal", "Water", "Cigarette"},
                {"Watch", "Look", "Stare", "Wrist", "Time", "Jewelery"},
                {"Brush", "Comb", "Hair", "Bristles", "Wooden", "Stroke"},
                {"License", "Driver", "Car", "Card", "Permit", "Allow"},
                {"Librarian", "Books", "Library", "School", "Job", "Quiet"},
                {"Liberty", "Freedom", "Statue", "Power", "Choose", "Decide"},
                {"Radio", "Listen", "Music", "AM", "FM", "News"},
                {"Shout", "Yell", "Loud", "Speak", "Angry", "Danger"},
                {"Unlock", "Key", "Door", "Box", "Safe", "Hole"},
                {"Pear", "Apple", "Fruit", "Shape", "Tree", "Juice"},
                {"Jumping", "Leap", "Up", "Down", "Excited", "Action"},
                {"Glove", "Hand", "Cold", "Winter", "Disposable", "Mitten"},
                {"Tornado", "Storm", "Dorothy", "Swirl", "Wind", "Blow"},
                {"Wheelchair", "Cripple", "Handicapped", "Legs", "Old", "Elderly"},
                {"Monster", "Scary", "Green", "Alien", "Zombie", "Creature"},
                {"Midterm", "Test", "Exam", "Half", "Final", "School"},
                {"Melt", "Soft", "Warm", "Ice", "Heat", "Liquid"},
                {"Mature", "Old", "Wise", "Develop", "Grown", "Advance"},
                {"Daisy", "White", "Yellow", "Flower", "Duck", "Field"},
                {"Custom", "Culture", "Way", "Tradition", "Behave", "Society"},
                {"Curtain", "Red", "Window", "Light", "Cloth", "Play"},
                {"Cruel", "Mean", "Angry","Unkind", "Pain", "Suffering"},
                {"Milk", "White", "Liquid", "Drink", "Bones", "Cow"},
                {"Politics", "Law", "President", "Leaders", "Country", "Citizen"},
                {"Guitar", "Instrument", "Play", "Strings", "Strum", "Music"},
                {"Chalk", "White", "Dust", "Teach", "Blackboard", "Erase"},
                {"Bottle", "Feed", "Baby", "Glass", "Juice", "Water"},
                {"Table", "Eat", "Chairs", "Legs", "Study", "Wooden"},
                {"Distance", "Length", "Mile", "Meter", "Space", "Far Away"},
                {"Elderly", "Old", "Nurse", "Aged", "Adult", "Health"},
                {"Fish", "Swim", "Gills", "River", "Eat", "Catch"},
                {"Famous", "Popular", "Known", "Important", "Recognize", "Position"},
                {"New York", "Statue", "Apple", "City", "America", "Busy"},
                {"Train", "Ride", "Travel", "Cheap", "Railroad", "Choo-choo"},
                {"Needle", "Haystack", "Sharp", "Small" ,"metal", "Sew"},
                {"Joy", "Happy", "Celebrate", "Excited", "Pleasure", "Feeling"},
                {"Firecracker", "Explode", "Loud", "Red", "Light", "Holiday"},
                {"Superman", "Fly", "Hero", "Bird", "Plane", "Clark Kent"},
                {"Sun", "Warm", "Yellow", "Light", "Solar", "Planet"},
                {"Monkey", "Swing", "Banana", "Zoo", "Brown", "Animal"},
                {"Shark", "Swim", "Teeth", "Fish", "Ocean", "Dangerous"},
                {"Desk", "Homework", "Sit", "Wooden", "Table", "Classroom"},
                {"Coffee", "Tea", "Drink", "Awake", "Starbucks", "CCD"},
                {"Egg Roll", "Spring", "Vegetable", "Round", "Chaina", "Food"},
                {"Santa", "Fat", "Christmas", "Gifts", "Red", "North Pole"},
                {"Bells", "Ring", "Silver", "Hear", "Metal", "Gold"},
                {"Heart", "Love", "Shape", "Beat", "Broken", "Blood"},
                {"Headache", "Pound", "Medicine", "Sick", "Brain", "Rush"},
                {"Discuss", "Talk", "Debate", "Ideas", "Oppose", "Share"},
                {"Debate", "Discus", "Sides", "Talk", "Oppose", "Win"},
                {"Eraser", "Clean", "Pencil", "Fix", "Mistake", "Change"},
                {"Prisoner", "Jail", "Convict", "Murder", "Crime", "Police"},
                {"Murder", "Kill", "Prison", "Jail", "Law", "Court"},
                {"Defend", "Lawyer", "Judge", "Stand Up", "Justify", "Reality"},
                {"Deer", "Animal", "Antlers", "Hunting", "Forest", "Bambi"},
                {"Zoo", "Animals", "Place", "Tigers", "Elephants", "Cage"},
                {"Crawl", "Fours", "Baby", "Toddlers", "Hands", "Knees"},
                {"Bank", "Robbery", "Money", "Safe", "Deposit", "Invest"},
                {"Caterpillar", "Crawl", "Insect", "Tree", "Butterfly", "Transformation"},
                {"Pregnant", "Baby", "Fat", "Belly", "Life", "9 Months"},
                {"Towel", "Dry", "Dishes", "Shower", "Soft", "Beach"},
                {"Promise", "Vow", "Pledge", "Expect", "Reassure", "Marry"},
                {"Ugly", "Duck", "Beautiful", "Hideous", "Deformed", "Butt"},
                {"Stupid", "Smart", "Cleaver", "Dull", "Dumb", "Intelligent"},
                {"Spoon", "Fork", "Knife", "Eating", "Soup", "Metal"},
                {"Infant", "Baby", "Cry", "Child", "Newborn", "Young"},
                {"Paris", "Romantic", "Shopping", "France", "Eiffel", "Tower"},
                {"Exchange Student", "Travel", "Study", "Abroad", "Experience", "Foreign"},
                {"Gold", "Silver", "Metal", "Rich", "Money", "King"},
                {"London", "England", "Europe", "U.K.", "Capital", "Big Ben"},
                {"Camping", "Tent", "Outside", "Fire", "Roast", "Sleep"},
                {"Theater", "Movie", "Drama", "Popcorn", "Cinema", "Actor"},
                {"Death", "Die", "Old", "Murder", "Life", "Cause"},
                {"Flag", "Wave", "Fly", "Old Glory", "Pole", "Fabric"},
                {"Describe", "Talk About", "Words", "Characteristics", "Quality", "Depict"},
                {"Fly", "Wings", "Bird", "Airplane", "Insect", "Bee"},
                {"Knee", "Bend", "Joint", "Leg", "Body Part", "Cap"},
                {"Web", "Internet", "Spider", "World Wide", "Net" , "Network"},
                {"Worm", "Crawl", "Animal", "Wriggle", "Slimy", "Rain"},
                {"Machine", "Parts", "Device", "Metal", "Power", "Cog"},
                {"Spiderman", "Peter Parker", "Marvel", "Comic Hero", "Webs", "Insect"},
                {"Waitress", "Service", "Restaurant", "Food", "Helper", "Worker"},
                {"Wash", "Clean", "Shower", "Dishes", "Hair", "Laundry"},
                {"Biology", "Sceince", "Subject", "Life", "School", "Cell"},
                {"Chemistry", "Sceince", "Subject", "Chemicals", "School", "Major"},
                {"History", "Politics", "Past", "Events", "Finished", "Happened"},
                {"Magazine", "Pages", "Book", "Entertain", "News", "Read"},
                {"Unfair", "Unjust", "Fair", "Equal", "Unreasonable", "Breakup"},
                { "CD", "Computer", "Disc", "Music", "Movies", "Play"},
                {"Immediately", "Fast", "Now", "Delay", "Rapid", "Soon"},
                {"Danger", "Safe", "Harm", "Injury", "Protect", "Avoid"},
                {"Blanket", "Bed", "Pillow", "Quilt", "Soft", "Warm"},
                {"Ice", "Cold", "Solid", "Water", "Freezer", "Winter"},
                {"Salt", "White", "Food", "Popcorn", "Cooking", "Flavour"},
                {"Stand", "Sit", "Floor", "Feet", "Up", "Take"},
                {"Bull", "Ride", "Animal", "Strong", "Farm", "Red"},
                {"Peaceful", "Harmony", "Calm", "Quiet", "Tranquil", "Violent"},
                {"Normal", "Strange", "Standard", "Typical", "Weird", "Status Quo"},
                {"Original", "First", "Unique", "Special", "Standard", "Early"},
                {"Magic", "Wizard", "Witch", "Power", "Trick", "Show"},
                {"Naughty", "Bad", "Behavior", "Good", "Rude", "Disobedient"},
                {"Rescue", "Save", "Hero", "Danger", "Safe", "Help"},
                {"Match", "Fire", "Strike", "Pair", "Game", "Equal"},
                {"Hippo", "Fat" ,"Animal", "Africa", "Large", "Water"},
                {"Fairy Tale", "Prince", "Magic", "Queen", "Story", "Fiction"},
                {"Literature", "Works", "American", "British", "Books", "Written"},
                {"Globe", "Earth", "World", "Model", "Geography", "Round"},
                {"Cook Book", "Food", "How to", "Kitchen", "Manual", "Guide"},
                {"Continent", "Ocean", "Asia", "Land", "Seven", "Earth"},
                {"Director", "Movie", "Producer", "Main", "In Charge", "Position"},
                {"Advice", "Guide", "Wise", "Recommend", "What to do", "Help"}
        };
                return allwords;





        }
    }
